samples/legacyScriptExemple.sh
src/main/bash/lib/scripts
src/main/python/SetupWindow/SetupWindowNetcatCommandParser.py

Initial implementation of POL_Download.
I hope I understood the system correctly.

[FIX] [Github #7] Implement POL_Download

---

src/main/java/com/playonlinux/ui/impl/javafx/installwindow/InstallWindow.java

It's not the most beautiful, but it probably is as beautiful as a UI from me will ever get. :)
Should the font-size of the message be increased?

[FIX #6] Add scene for download failure to the InstallWindow.

---

src/main/java/com/playonlinux/ui/impl/javafx/installwindow/InstallWindow.java

I rewrote InstallWindow's mainScene with automatic sizing by using the BorderPane and its regions.

Rewrote InstallWindow's mainScene with automatic sizing.

---

src/main/java/com/playonlinux/ui/impl/javafx/installwindow/InstallWindow.java

I rewrote InstallWindow's mainScene with automatic sizing by using the BorderPane and its regions.
Now that I've been at it, I implemented the filter checkboxes as well.

Rewrote InstallWindow with automatic sizing.

---

src/main/java/com/playonlinux/wine/WinePrefix.java

[WinePrefix] Cleaning

---

src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/MainWindow.java

We must confirm when exiting (like POLv4)
Now, closing the mainWindows close all the program

Add confirm popup when exit

---

src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/MainWindow.java

[Main Window] Simplify MainWindow exit code

[Main Window] Simplify MainWindow exit code

---

src/main/java/com/playonlinux/app/PlayOnLinuxApp.java
src/main/java/com/playonlinux/app/PlayOnLinuxConfig.java
src/main/java/com/playonlinux/common/api/services/BackgroundServiceManager.java
src/main/java/com/playonlinux/common/dto/ProgressStateDTO.java
src/main/java/com/playonlinux/common/services/EventHandlerPlayOnLinuxImplementation.java
src/main/java/com/playonlinux/common/services/InstalledApplicationsPlayOnLinuxImplementation.java
src/main/java/com/playonlinux/common/services/InstalledVirtualDrivesPlayOnLinuxImplementation.java
src/main/java/com/playonlinux/common/services/PlayOnLinuxBackgroundServicesManager.java
src/main/java/com/playonlinux/common/services/RemoteAvailableInstallersPlayOnLinuxImplementation.java
src/main/java/com/playonlinux/domain/ShortcutSet.java
src/main/java/com/playonlinux/framework/WinePrefix.java
src/main/java/com/playonlinux/injection/Injector.java
src/main/java/com/playonlinux/ui/impl/javafx/setupwindow/StepRepresentationProgressBar.java
src/main/java/com/playonlinux/utils/AbstractObservableDirectory.java
src/main/java/com/playonlinux/utils/ObservableDirectoryFiles.java
src/main/java/com/playonlinux/utils/ObservableDirectorySize.java
src/main/java/com/playonlinux/webservice/HTTPDownloader.java
src/main/java/com/playonlinux/webservice/InstallerSourceWebserviceImplementation.java
src/main/java/com/playonlinux/wine/WinePrefix.java
src/test/java/com/playonlinux/utils/ObservableDirectoryFilesTest.java

[Utils] Implementing observable directory size

[Utils] Implementing observable directory size

---

.gitignore
src/main/bash/lib/config.sh
src/main/bash/lib/debug.sh
src/main/bash/lib/netcat.sh
src/main/bash/lib/scripts.sh
src/main/bash/lib/setupWindow.sh
src/main/bash/lib/sources
src/main/bash/lib/system.sh
src/main/bash/lib/wine.sh
src/main/python/BashBinder/CommandParser.py

- Add POL_SetupWindow_free_presentation and POL_SetupWindow_presentation for v4 compatibility
- Replace TAB on bash file with space
!> And just replace some \\t and \t I remove accidently on netcat.sh

Add two POLv4 commande

---

src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/center/CategoryView.java
src/main/resources/com/playonlinux/ui/impl/javafx/common/common.css

[JavaFX] Improve Install icon alignment

[JavaFX] Improve Install icon alignment

---

src/main/java/com/playonlinux/wine/WindowsShortcut.java

- "Rename this field name to match the regular expression" (minor)
- "This block of commented-out lines of code should be removed" (major)
But not tested (the compilation is ok)

[WindowsShortcut] fix SonarQube minor and major

---

src/main/bash/lib/setupWindow.sh
src/main/java/com/playonlinux/framework/SetupWizard.java
src/main/python/BashBinder/CommandParser.py

presentation() have two methode now, one for free presentation and one with default text format. The second way support translation system (but may be updated for use the new variable)
+ Some correction for javadoc ;)

Add default presentation system

---

src/main/java/com/playonlinux/common/filter/InstalledApplicationFilter.java
src/test/java/com/playonlinux/common/filter/InstalledApplicationFilterTest.java

* Add a unit test for InstalledApplicationFilter

    * [MainWindow SearchBox] - hotfixes

---

src/main/java/com/playonlinux/dto/ui/AppsItemDTO.java
src/main/java/com/playonlinux/services/RemoteAvailableInstallersPlayOnLinuxImplementation.java
src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/apps/AppPanel.java
src/main/resources/com/playonlinux/ui/impl/javafx/common/common.css
src/main/resources/com/playonlinux/ui/impl/javafx/mainwindow/apps/descriptionTemplate.html

[UI] Loading the scripts miniatures from the UI

[UI] Loading the scripts miniatures from the UI

---

src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/MainWindow.java

Don't merge now, I will try to correct name into menubar too (see https://github.com/PlayOnLinux/POL-POM-5/issues/107)

[MainWindow] add icon on gnome menubar

---

src/main/java/com/playonlinux/ui/impl/javafx/setupwindow/StepRepresentationLicence.java
src/main/resources/playonlinux.properties

+ Add missing properties for POL
It's ok now ? :)

[StepRepresentationLicence] Modify disposition

---

src/main/java/com/playonlinux/installer/Script.java

Maybe it's not the better way, I don't know how the ExecutorService object work. But I found that was one of his Thread the problem (with his name "pool-5"). Actually, the problematic Thread close and the app can correctly close :)

Correct Thread not closing after launch a script

---

src/main/java/com/playonlinux/app/PlayOnLinuxConfig.java
src/main/java/com/playonlinux/python/JythonCommandInterpreterFactory.java
src/test/java/com/playonlinux/MockContextConfig.java

[Config] Fix executor service resource problem

[Config] Fix executor service resource problem

---

src/main/java/com/playonlinux/ui/impl/javafx/consolewindow/ConsoleWindow.java

Implemented a simple CommandHistory within the ConsoleWindow which can be navigated by the up and down keys.

[ConsoleWindow] Implemented a simple CommandHistory for convenience

---

src/main/java/com/playonlinux/ui/impl/qt/UIMessageSenderQtImplementation.java

Initial implementation of the UIMessageSender for POL's Qt-Gui.

[Qt] Implement UIMessageSender

---

src/main/java/com/playonlinux/engines/wine/DefaultWineVersionsManager.java
src/main/java/com/playonlinux/engines/wine/WineVersionManager.java
src/main/java/com/playonlinux/ui/impl/javafx/JavaFXApplication.java
src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/MessagePanel.java
src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/containers/EventHandlerContainers.java
src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/containers/WinePrefixContainerConfigurationView.java
src/main/java/com/playonlinux/ui/impl/javafx/setupwindow/AbstractStepRepresentation.java
src/main/java/com/playonlinux/ui/impl/javafx/setupwindow/SetupWindowJavaFXImplementation.java
src/main/java/com/playonlinux/ui/impl/qt/ControllerQtImplementation.java
src/main/java/com/playonlinux/ui/impl/qt/common/IconHelper.java
src/main/java/com/playonlinux/ui/impl/qt/common/QMemoryStream.java
src/main/java/com/playonlinux/ui/impl/qt/mainwindow/MainWindow.java
src/main/java/com/playonlinux/ui/impl/qt/mainwindow/menubar/MenuBar.java

removed all unused Imports listed on http://qparis.net:9000/component_issues/index?id=com.playonlinux:playonlinux#resolved=false|rules=squid%3AUselessImportCheck 
Is there a more general place to ask questions/discuss them?
I'd like to work on the GTK implementation of the interface. How can i test the other UI Implementations?

removed some unused imports

---

src/main/java/com/playonlinux/containers/WineContainerEventHandler.java
src/main/java/com/playonlinux/core/streams/ProcessPipe.java
src/main/java/com/playonlinux/framework/Wine.java
src/main/java/com/playonlinux/framework/WineShortcut.java
src/main/java/com/playonlinux/library/LibraryEventHandler.java
src/main/java/com/playonlinux/library/runners/WineShortcutRunner.java
src/main/java/com/playonlinux/library/shortcuts/WineShortcut.java
src/main/java/com/playonlinux/ui/events/EventHandler.java
src/main/java/com/playonlinux/ui/events/EventHandlerPlayOnLinuxImplementation.java
src/main/java/com/playonlinux/ui/impl/javafx/common/ErrorMessage.java
src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/library/EventHandlerLibrary.java
src/main/java/com/playonlinux/wine/WineConstants.java
src/main/resources/playonmac.properties

Ability to run shortcuts

---

phoenicis-core/src/main/java/com/playonlinux/framework/Files.java
phoenicis-core/src/test/java/com/playonlinux/core/python/PythonInstallerTest.java
phoenicis-core/src/test/java/com/playonlinux/core/utils/ChecksumCalculatorTest.java
phoenicis-core/src/test/java/com/playonlinux/core/utils/ObservableDirectoryFilesTest.java
phoenicis-javafx/src/test/java/com/playonlinux/ui/impl/javafx/common/HtmlTemplateTest.java
phoenicis-wine/src/test/java/com/playonlinux/wine/WineTest.java
phoenicis-wine/src/test/java/com/playonlinux/wine/registry/RegistryParserTest.java

Correct a bunch of resource Leak warnings. Most of them was in test files.
The recommended way of handling autocloseable resources is through try with resource since Java 7. Might be a good idea to enforce this in the futur.

[Warning Correction] Resource Leak

---

phoenicis-wine/src/main/java/com/playonlinux/wine/configurations/RegistryWinePrefixDisplayConfiguration.java
phoenicis-wine/src/main/java/com/playonlinux/wine/configurations/RegistryWinePrefixInputConfiguration.java
phoenicis-wine/src/test/java/com/playonlinux/wine/registry/RegistryParserTest.java

Fix the easy unchecked cast Warnings

Fix unchecked cast

---

phoenicis-core/src/main/java/com/playonlinux/framework/Downloader.java
phoenicis-core/src/main/java/com/playonlinux/framework/Files.java
phoenicis-core/src/main/java/com/playonlinux/framework/SystemUtilities.java
phoenicis-wine/src/main/java/com/playonlinux/framework/Wine.java
phoenicis-wine/src/main/java/com/playonlinux/framework/WineVersion.java

Removing unnecessary SuppressWarnings

Fix Unnecessary SuppressWarnings

---

phoenicis-core/src/main/java/com/playonlinux/app/PlayOnLinuxException.java
phoenicis-core/src/main/java/com/playonlinux/app/PlayOnLinuxRuntimeException.java
phoenicis-core/src/main/java/com/playonlinux/apps/AppsManagerException.java
phoenicis-core/src/main/java/com/playonlinux/core/gpg/SignatureException.java
phoenicis-core/src/main/java/com/playonlinux/core/python/CommandInterpreterException.java
phoenicis-core/src/main/java/com/playonlinux/core/python/PythonException.java
phoenicis-core/src/main/java/com/playonlinux/core/scripts/CancelException.java
phoenicis-core/src/main/java/com/playonlinux/core/scripts/ScriptFailureException.java
phoenicis-core/src/main/java/com/playonlinux/core/services/manager/ServiceException.java
phoenicis-core/src/main/java/com/playonlinux/core/services/manager/ServiceInitializationException.java
phoenicis-core/src/main/java/com/playonlinux/core/utils/ReplacableProperties.java
phoenicis-core/src/main/java/com/playonlinux/core/utils/archive/ArchiveException.java
phoenicis-core/src/main/java/com/playonlinux/core/utils/archive/cab/CabException.java
phoenicis-core/src/main/java/com/playonlinux/core/webservice/DownloadException.java
phoenicis-core/src/main/java/com/playonlinux/engines/wine/EngineInstallException.java
phoenicis-core/src/main/java/com/playonlinux/library/LibraryException.java
phoenicis-injection/src/main/java/com/playonlinux/injection/InjectionException.java
phoenicis-wine/src/main/java/com/playonlinux/wine/UninitializedWineprefixException.java
phoenicis-wine/src/main/java/com/playonlinux/wine/WineException.java
phoenicis-wine/src/main/java/com/playonlinux/wine/registry/RegistryException.java

Fixing Missing SerialVersionUID Warnings by adding generated SerialVersionUID

Fix warning serial version uid

---

phoenicis-core/src/main/java/com/playonlinux/apps/AppsManager.java
phoenicis-core/src/main/java/com/playonlinux/apps/DefaultAppsManager.java
phoenicis-core/src/main/java/com/playonlinux/core/scripts/InstallerSource.java
phoenicis-core/src/main/java/com/playonlinux/core/webservice/Webservice.java
phoenicis-core/src/main/java/com/playonlinux/engines/wine/DefaultWineVersionsManager.java
phoenicis-core/src/main/java/com/playonlinux/engines/wine/WineVersionManager.java
phoenicis-core/src/main/java/com/playonlinux/engines/wine/WineVersionSource.java
phoenicis-core/src/test/java/com/playonlinux/core/webservice/InstallerSourceWebserviceImplementationTest.java

Removed observer pattern for web service

Removed observer pattern for web service

---

phoenicis-core/src/main/java/com/playonlinux/apps/DefaultInstallerDownloaderEntityProvider.java
phoenicis-core/src/main/java/com/playonlinux/core/python/CommandInterpreter.java
phoenicis-core/src/main/java/com/playonlinux/core/python/JythonCommandInterpreter.java
phoenicis-core/src/main/java/com/playonlinux/core/services/SubmittableService.java
phoenicis-core/src/main/java/com/playonlinux/core/utils/archive/Extractor.java
phoenicis-core/src/main/java/com/playonlinux/core/utils/archive/Tar.java
phoenicis-core/src/main/java/com/playonlinux/core/webservice/DownloadManager.java
phoenicis-core/src/test/java/com/playonlinux/core/webservice/DownloadManagerTest.java
phoenicis-javafx-wine/src/main/java/com/playonlinux/javafx/containers/WinePrefixContainerConfigurationView.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/common/RemoteImage.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/mainwindow/console/ConsoleTab.java
phoenicis-wine/src/main/java/com/playonlinux/containers/WineContainerActions.java

Function<*, Void> is basically a Consumer

Using Consumer instead of Function<*, Void>

---

phoenicis-app/pom.xml
phoenicis-apps/pom.xml
phoenicis-bash/pom.xml
phoenicis-core/pom.xml
phoenicis-integration/pom.xml
phoenicis-javafx-wine/pom.xml
phoenicis-javafx/pom.xml
phoenicis-qt/pom.xml
phoenicis-ui/pom.xml
phoenicis-wine/pom.xml
pom.xml

Fix maven warnings

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/common/PlayOnLinuxScene.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/common/Themes.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/common/hidpiTheme.css

first pass at creating a hidpi theme.  This fixes almost everything, text on the menu on left and dropdowns is still too small.

added hidpi theme

---

phoenicis-configuration/src/main/resources/Linux.properties

fixes crash on startup on Linux

added wineprefix to Linux.properties

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/MainController.java

fixes: Window title is NULL #351

fixed missing window title

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/MainWindowHeader.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/darkTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/defaultTheme.css

fixes: Highlight currently selected tab in JavaFX #345

use TabPane for menu

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/MainController.java

fixes: Center close button on PoL window instead of screen #356

set owner for close alert

---

phoenicis-apps/src/main/java/com/playonlinux/apps/ApplicationsSource.java
phoenicis-apps/src/main/java/com/playonlinux/apps/AppsConfiguration.java
phoenicis-apps/src/main/java/com/playonlinux/apps/BackgroundApplicationsSource.java
phoenicis-apps/src/main/java/com/playonlinux/apps/GitApplicationsSource.java
phoenicis-apps/src/main/java/com/playonlinux/apps/LocalApplicationsSource.java
phoenicis-apps/src/main/java/com/playonlinux/apps/TeeApplicationsSource.java
phoenicis-apps/src/main/java/com/playonlinux/apps/dto/CategoryDTO.java
phoenicis-cli/src/main/java/com/playonlinux/cli/CLIController.java
phoenicis-configuration/src/main/resources/Linux.properties
phoenicis-configuration/src/main/resources/Mac OS X.properties
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/apps/AppsController.java
phoenicis-scripts/src/main/java/com/playonlinux/scripts/ScriptsConfiguration.java

Merge applications from git and ${application.user.repository}.
fixes: Implement TeeApplicationsSource #332 
This should also have a unit test. However, the complete unit test setup does not yet exist for phoenicis-apps and I didn't want to add it with this pull request.

implemented TeeApplicationsSource

---

phoenicis-apps/pom.xml
phoenicis-apps/src/main/java/com/playonlinux/apps/AppsConfiguration.java
phoenicis-apps/src/main/java/com/playonlinux/apps/FilterApplicationSource.java
phoenicis-apps/src/main/java/com/playonlinux/apps/dto/CategoryDTO.java
phoenicis-configuration/src/main/resources/Linux.properties
phoenicis-configuration/src/main/resources/Mac OS X.properties
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/MainController.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/darkTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/defaultTheme.css
phoenicis-tools/src/main/java/com/playonlinux/tools/files/DirectoryWatcher.java

Default window height fit install window

Default window height fit install window

---

phoenicis-scripts/src/main/java/com/playonlinux/scripts/wizard/SetupWizard.java

SetupWizard: surrond app name with ""

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/library/ViewLibrary.java

fixes: JavaFx shows app in sidebar after uninstall #406

clear sidebar on app uninstall

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/common/ConfirmMessage.java

fixes: Question to remove container after removing app is not shown correctly #432

adjust ConfirmMessage size depending on text

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/common/widget/MiniatureListWidget.java

Hide scrollbar

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/common/widget/MiniatureListWidget.java

Reverts PlayOnLinux/POL-POM-5#440
Doesn't build.

Revert "Hide scrollbar"

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/MainWindowView.java

fixes: JavaFx: "Containers" doesn't scale #443

size containers with window size

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/engines/ViewEngines.java

fixes: JavaFx: "Engines" doesn't scale #444

size engines list with window size

---

phoenicis-scripts/src/main/java/com/playonlinux/scripts/wizard/SetupWizard.java
phoenicis-scripts/src/main/java/com/playonlinux/scripts/wizard/SetupWizardFactory.java

SetupWizard.browse() use user home as default

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/setupwindow/AbstractStepRepresentationWithHeader.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/setupwindow/StepRepresentationMessage.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/darkTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/defaultTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/hidpiTheme.css

fixes: Text needs to be wrapped and scaled #449

wrap text in StepRepresentationMessage

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/setupwindow/StepRepresentationMessage.java

Fix Scaling of Messages

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java

fixed information layout

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java

fixed display settings layout

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/MainWindow.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/MainWindowView.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/settings/ViewSettings.java

fixes:
- Containers don't get added to view after installation until restart of app #466
- Containers don't get removed from view until restart of app after uninstall #467

update containers when "Containers" tab is opened 

---

phoenicis-containers/src/main/java/com/playonlinux/containers/BackgroundContainersManager.java
phoenicis-containers/src/main/java/com/playonlinux/containers/ContainersConfiguration.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/MainWindowView.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-multithreading/src/main/java/com/playonlinux/multithreading/MultithreadingConfiguration.java

fixes: 
- App hangs when switching from and to containers #470
- Container main window doesn't get refreshed after uninstall #469

asynchronous update for containers

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/containers/ContainersController.java
phoenicis-multithreading/src/main/java/com/playonlinux/multithreading/MultithreadingConfiguration.java

Before, the update was also done when the "Containers" tab was closed.

update containers only when "Containers" tab is opened

---

phoenicis-containers/src/main/java/com/playonlinux/containers/dto/ContainerDTO.java
phoenicis-containers/src/main/java/com/playonlinux/containers/wine/WinePrefixesManager.java

sort containers

---

phoenicis-javafx/pom.xml
phoenicis-javafx/src/main/java/com/playonlinux/javafx/AppConfiguration.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/settings/SettingsController.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-settings/pom.xml
phoenicis-settings/src/main/java/com/phoenicis/settings/Setting.java
phoenicis-settings/src/main/java/com/phoenicis/settings/Settings.java
phoenicis-settings/src/main/java/com/phoenicis/settings/SettingsConfiguration.java
phoenicis-settings/src/main/java/com/phoenicis/settings/SettingsManager.java
phoenicis-settings/src/main/java/com/phoenicis/settings/SettingsSaver.java
pom.xml

Save user settings in a user specific properties file.

Save settings (fixes #365)

---

phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/darkTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/defaultTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/hidpiTheme.css

fixed CSS for LeftButton text

---

phoenicis-tools/src/test/java/com/playonlinux/tools/system/terminal/AutomaticTerminalOpenerTest.java

Automatic terminal opener unit test

Automatic terminal opener unit test

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-settings/src/main/java/com/phoenicis/settings/SettingsManager.java

settings: use list for repositories

---

phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/darkTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/defaultTheme.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/hidpiTheme.css

Before, the tab lost its highlighting once it lost focus (e.g. if you clicked any button).

fixed highlighting of active tab in menu

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/common/Themes.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/views/common/breezeDarkTheme.css

Plasma 5 Breeze Dark Theme

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/setupwindow/StepRepresentationMessage.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/setupwindow/StepRepresentationProgressBar.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/breezeDark/descriptionTemplate.html
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/breezeDark/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/default/main.css

fixes #496
Somehow, I have problems changing the text color. Could need some help there.

Breeze Dark: dark background for installation

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/controller/library/console/ConsoleController.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/console/ConsoleTab.java
phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/console/ConsoleTextType.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/breezeDark/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/default/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/hidpi/main.css

make console text styleable in theme

---

phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/breezeDark/main.css

fixed progress bar in Breeze Dark

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/setupwindow/StepRepresentationPresentation.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/breezeDark/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/default/main.css
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/hidpi/main.css

fixes #515
Might need some fine tuning in the CSS later on.

made presentation styleable

---

phoenicis-entities/src/main/java/com/phoenicis/entities/OperatingSystem.java
phoenicis-entities/src/main/java/com/phoenicis/entities/ProgressEntity.java
phoenicis-javafx/pom.xml
phoenicis-tools/src/test/java/com/phoenicis/entities/ArchitectureTest.java
phoenicis-tools/src/test/java/com/phoenicis/entities/ProgressEntityTest.java
phoenicis-win32/src/main/java/com/playonlinux/win32/pe/PEFile.java

Unit tests for phoenicis-entities

Unit tests for phoenicis-entities

---

phoenicis-apps/src/main/java/com/playonlinux/apps/ClasspathApplicationsSource.java

sort fetched applications of ClasspathApplicationsSource

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/common/Themes.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/unity/descriptionTemplate.html
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/unity/main.css

fixes #529 
@Ads20000 what do you think?

added Unity theme

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/ui/LeftBarTitle.java
phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/unity/main.css

@Ads20000 like this?
I tried to change the tabs but it doesn't look good.

Unity refinements

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/settings/ViewSettings.java

removed settings save button

---

phoenicis-javafx/src/main/resources/com/playonlinux/javafx/themes/unity/main.css

fixed: text field not visible in wizard with Unity theme

---

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/setupwindow/StepRepresentationTextBox.java

disable next button if no text entered in wizard

---

phoenicis-configuration/src/main/resources/Linux.properties
phoenicis-library/src/main/java/com/phoenicis/library/LibraryConfiguration.java
phoenicis-library/src/main/java/com/phoenicis/library/ShortcutManager.java

create .desktop file (on Linux) when shortcut is created

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/hidpi/main.css

Refactored themes

---

phoenicis-configuration/src/main/resources/Mac OS X.properties

Allows POM to run

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/PhoenicisScene.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css

- fixes #542 
- fixes #536
There is an issue with tabs:
@qparis do you have an idea what I need to do to fix this?

use StyleManager to change theme

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/PhoenicisScene.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css

Reverts PlayOnLinux/POL-POM-5#571
It seems like StyleManager is part of an officially unsupported API (in `com.sun`) which causes several issues and should not be used.

Revert "use StyleManager to change theme"

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java

make sure that theme is applied to repository dialog

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/AppConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ThemeConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/PhoenicisScene.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/Theme.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ThemeConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ThemeManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/FailurePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindow.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindowView.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewsConfigurationLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/hidpi/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css

made ThemeManager a spring bean

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ThemeManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/hidpi/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css

The previous solution did not work properly because setStyle always overrides the CSS.

fixed themed category icons

---

phoenicis-cli/src/main/java/org/phoenicis/cli/setupwindow/SetupWindowCLIImplementation.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/SetupWindowJavaFXImplementation.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/StepRepresentationMenu.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/SetupWindow.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/ChoiceWizard.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/SetupWizard.java
phoenicis-tests/src/main/java/org/phoenicis/tests/TestSetupWindow.java

added option to specify default value for menu in wizard

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java

added hint to restart to load icon theme

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/FailurePanel.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/hidpi/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css

made retry icon resizable from theme

---

phoenicis-cli/src/main/java/org/phoenicis/cli/setupwindow/SetupWindowCLIImplementation.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/SetupWindowJavaFXImplementation.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/StepRepresentationMenu.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/MenuItem.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/SetupWindow.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/ChoiceWizard.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/SetupWizard.java
phoenicis-tests/src/main/java/org/phoenicis/tests/TestSetupWindow.java

wizard menu step: return index of selected element

---

phoenicis-cli/pom.xml
phoenicis-cli/src/main/java/org/phoenicis/cli/setupwindow/SetupWindowCLIImplementation.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/JavaFXSetupWindowUIConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/SetupWindowJavaFXImplementation.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/StepRepresentationHtmlPresentation.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/setupwindow/StepRepresentationPresentation.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/description.css
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/SetupWindow.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/CompleteWizard.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/SetupWizard.java
phoenicis-tests/src/main/java/org/phoenicis/tests/TestSetupWindow.java

Now, e.g. links can actually be links and not just plain text.
fixes #428

enable a rich text presentation in the setup wizard

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java

do not show an error message if the installation is cancelled

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java

In preparation for a fix for #528

added engine panel

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java

gray scale for not installed wine versions

---

phoenicis-containers/pom.xml
phoenicis-containers/src/main/java/org/phoenicis/containers/ContainersConfiguration.java
phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WineContainerController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java

added possibility to delete a wine prefix

---

phoenicis-apps/src/main/java/org/phoenicis/apps/AppsConfiguration.java
phoenicis-apps/src/main/java/org/phoenicis/apps/CachedApplicationsSource.java
phoenicis-apps/src/test/java/org/phoenicis/apps/CachedApplicationsSourceTest.java

implemented CachedApplicationsSource

---

phoenicis-engines/src/main/java/org/phoenicis/engines/dto/WineEngineDTO.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java

New DTO containing the information required to install/delete a wine engine.
Required by #614 and #615.

implemented WineEngineDTO

---

phoenicis-apps/src/main/java/org/phoenicis/apps/ApplicationsSource.java
phoenicis-apps/src/main/java/org/phoenicis/apps/AppsFilter.java
phoenicis-apps/src/main/java/org/phoenicis/apps/AppsSearchFilter.java
phoenicis-apps/src/main/java/org/phoenicis/apps/BackgroundApplicationsSource.java
phoenicis-apps/src/main/java/org/phoenicis/apps/CombinedAppsFilter.java
phoenicis-apps/src/main/java/org/phoenicis/apps/FilterApplicationsSource.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java

implemented apps search

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java

Delay the search by 0.5 seconds so it does not search for every character you type.
fixes #651

delay app search

---

README.md

see: <https://github.com/PlayOnLinux/POL-POM-5/wiki/Eclipse>

moved Eclipse description to wiki

---

phoenicis-javafx/pom.xml
phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java

Ok, this PR introduces a test for the Initialisation of the AppConfiguration.
The problem with this approach is, that it opens a gui-window, and I don't know if jenkins supports this...
If someone has a better approach or understands the API of testfx better than me, I'm open for suggestions :)

Added a test for the initialisation of the AppConfiguration class

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widget/MiniatureListWidget.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java

This PR is currently the first step to change the Apps tab to use an ObservableList to handle its content.
This makes it much easier to change the content of the Apps tab and to set filters and an ordering of the apps.

Use ObservableList for the MiniatureListWidget

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css

fixed tabs in Unity theme

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css

fixed tabs in Breeze Dark theme

---

phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java

delete desktop shortcut if app is uninstalled

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ExpandedList.java
phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/ExpandedListTest.java

This PR improves the implementation of the `ExpandedList` class.
In addition this PR introduces a new test and it extends the existing tests for the `ExpandedList` class.

Improved the ExpandedList implementation

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/MappedListTest.java

This PR introduces a new "refresh Repositories" button to the repository settings.

Added a "refresh Repositories" button to the repository settings

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftBarTitle.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftGroup.java

wrap side bar title

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerSideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java

This PR moved the code responsible for the sidebar in the Containers tab to a new class.
In addition it uses a LeftToggleGroup for the management of the container buttons in the sidebar.

Refactoring and improving the sidebar of the Containers tab

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftGroup.java

This PR refactors the class `LeftGroup`.
In addition it adds JavaDoc and only shows a Label for the title of the LeftGroup if a title has been set.

Refactored LeftGroup

---

phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/ExpandedListTest.java
phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/MappedListTest.java

Reinserted ignored tests

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindowView.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerSideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/SettingsSideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftSideBar.java

This PR refactors the `MainWindowView` and makes all sidebars extend `LeftSideBar`.

Refactored the class MainWindowView

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css

scale containers tab

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/Theme.java

it was still shown as option in the settings

removed obsolete HiDPI theme

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css

scale default theme

---

phoenicis-apps/src/main/java/org/phoenicis/apps/dto/CategoryDTO.java
phoenicis-apps/src/main/java/org/phoenicis/apps/repository/ClasspathRepository.java
phoenicis-apps/src/main/java/org/phoenicis/apps/repository/LocalRepository.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java

use URI for icon in CategoryDTO

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

use variables to define colors in themes

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

added missing "other" category icon to themes

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

fixed height of left buttons in Unity theme

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

updated Unity theme for list type selection

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.less

updated dark theme for list type selection

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

fixed padding of side bar buttons in Unity theme

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/description.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/description.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/description.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/description.less

The font size was either not scaled or too large (Breeze Dark).

fixed font size in description.less

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java

fixes  #796 (miniature not shown if path contains ')

quote URL for app miniatures

---

phoenicis-settings/src/main/java/org/phoenicis/settings/SettingsManager.java

See http://www.playonlinux.org:9000/issues#issues=AVnFemOEqDnz5jcTz9yV

Make sure FileOutputStream is closed

---

phoenicis-containers/src/main/java/org/phoenicis/containers/wine/configurations/RegistryWinePrefixContainerDisplayConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/StepRepresentationTextBox.java
phoenicis-tools/src/main/java/org/phoenicis/tools/files/DirectoryWatcher.java
phoenicis-tools/src/main/java/org/phoenicis/tools/system/terminal/MacOSTerminalOpener.java

http://www.playonlinux.org:9000/issues#issues=AVw-tQUD9U_f07q6H1DW
http://www.playonlinux.org:9000/issues#issues=AVw-tQAL9U_f07q6H0_W
http://www.playonlinux.org:9000/issues#issues=AVw-tQHA9U_f07q6H1Aw
http://www.playonlinux.org:9000/issues#issues=AVw-tQQc9U_f07q6H1Cp
http://www.playonlinux.org:9000/issues#issues=AVw-tQPW9U_f07q6H1Cb

SonarQube fixes

---

README.md

fixed broken SonarQube link in README

---

phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerToolsTab.java

added button to create a shortcut

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java

Add filter functionality for the unused checkboxes inside the "Apps" tab

---

phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/MergeableRepository.java

Remove the miniature duplicates during the merging of two applications

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/ListWidgetEntry.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ApplicationDTO.java

Add a new method getMainMiniature() to the ApplicationDTO

---

i18n/de.po
i18n/keys.pot
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ErrorMessage.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/themes/Themes.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerDisplayTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerInformationTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/SettingsSideBar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java

Make sure all relevant Strings are translated and add German translation.

German translation

---

phoenicis-repository/src/main/java/org/phoenicis/repository/DefaultRepositoryManager.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/RepositoryDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/TranslationDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/BackgroundRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/CachedRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/ClasspathRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/FilterRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/MergeableRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/MultipleRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/NullRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/Repository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/TeeRepository.java
phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/BackgroundRepositoryTest.java
phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/CachedRepositoryTest.java
phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/ClasspathRepositoryTest.java
phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/MultipleRepositoryTest.java
phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/NullRepositoryTest.java
phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/TeeRepositoryTest.java
phoenicis-tests/src/main/java/org/phoenicis/tests/MockedRepository.java
phoenicis-tests/src/main/java/org/phoenicis/tests/PhoenicisTestsApp.java
phoenicis-tests/src/test/java/org/phoenicis/tests/DTOContractTest.java

new hierarchy level above CategoryDTO
required by #872

added RepositoryDTO

---

phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/ClasspathRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java

load application.json in correct language

---

i18n/de.po
i18n/keys.pot
phoenicis-cli/src/test/resources/org/phoenicis/cli/testRepository/Graphics/Photofiltre/Online/script.json
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSideBar.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ScriptDTO.java
phoenicis-repository/src/test/resources/org/phoenicis/repository/repositoryTest/Development/Notepad++/v7.2.2/script.json
phoenicis-repository/src/test/resources/org/phoenicis/repository/repositoryTest/Graphics/Photofiltre/Online/script.json

fixes #860
requires PlayOnLinux/Scripts#252

renamed "requiresNoCD" to "requiresPatch"

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryPanel.java

fixed missing title in details panel

---

phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/ClasspathRepository.java

classpath repository: check if category.json exists

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryPanel.java
phoenicis-library/src/main/java/org/phoenicis/library/LibraryManager.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/MergeableRepository.java
phoenicis-tools/src/main/java/org/phoenicis/tools/system/terminal/MacOSTerminalOpener.java

When both key and value are accessed.
Sonarqube links:
http://www.playonlinux.org:9000/issues#issues=AVx8gCMNaOc448AVSn53
http://www.playonlinux.org:9000/issues#issues=AVxD2WxM9U_f07q6H1GT
http://www.playonlinux.org:9000/issues#issues=AVw-tQRw9U_f07q6H1Cw
http://www.playonlinux.org:9000/issues#issues=AVw-tQLl9U_f07q6H1BU
http://www.playonlinux.org:9000/issues#issues=AVw-tQLm9U_f07q6H1BV
http://www.playonlinux.org:9000/issues#issues=AVw-tQLm9U_f07q6H1BW
http://www.playonlinux.org:9000/issues#issues=AVw-tQQc9U_f07q6H1Co

Iterate over entrySet instead of keySet

---

phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java

fixes: http://www.playonlinux.org:9000/issues#issues=AVw-tQLX9U_f07q6H1BH

Close a Git in all situations

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less

Was using the ones inherited from the default theme.

Breeze Dark: fixed list chooser icons (when selected)

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftListWidgetChooser.java

list chooser: prevent unselecting all buttons

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindowView.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/SettingsSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftSidebar.java

This PR solves #904.
In addition it does some similar refactoring and it renames all occurrences of `SideBar` to `Sidebar`.

Refactoring of the MainWindowView and its implementing classes

---

phoenicis-configuration/src/main/resources/Linux.properties
phoenicis-configuration/src/main/resources/Mac OS X.properties
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindow.java
phoenicis-settings/src/main/java/org/phoenicis/settings/Setting.java
phoenicis-settings/src/main/java/org/phoenicis/settings/SettingsManager.java

When closing Phoenicis, remember the window size and whether or not it is maximized. Restore this state on next startup.

remember window size

---

i18n/de.po
i18n/keys.pot
phoenicis-cli/pom.xml
phoenicis-configuration/pom.xml
phoenicis-containers/pom.xml
phoenicis-dist/pom.xml
phoenicis-engines/pom.xml
phoenicis-entities/pom.xml
phoenicis-javafx/pom.xml
phoenicis-library/pom.xml
phoenicis-multithreading/pom.xml
phoenicis-repository/pom.xml
phoenicis-scripts/pom.xml
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/UiSetupWizardImplementation.java
phoenicis-settings/pom.xml
phoenicis-tests/pom.xml
phoenicis-tests/src/main/resources/org/phoenicis/tests/wine.js
phoenicis-tools/pom.xml
phoenicis-tools/src/main/java/org/phoenicis/tools/checksum/ChecksumCalculator.java
phoenicis-win32/pom.xml
pom.xml

fixed gettext-commons maven integration

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-library/src/main/java/org/phoenicis/library/LibraryManager.java

Has to be done after the repositories have been fetched to have the translation files.

translate shortcut categories in library tab

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftButton.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftToggleButton.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

fixed width of left sidebar

---

i18n/de.po
i18n/keys.pot
phoenicis-containers/src/main/java/org/phoenicis/containers/ContainersConfiguration.java
phoenicis-containers/src/main/java/org/phoenicis/containers/dto/ContainerDTO.java
phoenicis-containers/src/main/java/org/phoenicis/containers/dto/WinePrefixContainerDTO.java
phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainersManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/ListWidgetEntry.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerInformationTab.java

containers tab:
* show shortcuts using the container
* create container miniature by composing the miniatures of the shortcuts using this container

show shortcuts using a container

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/AbstractStepRepresentation.java

fixed wizard button width

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryPanel.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less

fixed shortcut button width

---

phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainersManager.java
phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineCategoryDTO.java
phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineDTO.java
phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineSubCategoryDTO.java
phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineVersionDTO.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/icons/IconsListElement.java
phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutCategoryDTO.java
phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryConfiguration.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ApplicationDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/CategoryDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/RepositoryDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ScriptDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/TranslationDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/location/ClasspathRepositoryLocation.java
phoenicis-repository/src/main/java/org/phoenicis/repository/location/GitRepositoryLocation.java
phoenicis-repository/src/main/java/org/phoenicis/repository/location/LocalRepositoryLocation.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/BackgroundRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/CachedRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/ClasspathRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/FilterRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/MultipleRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/NullRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/TeeRepository.java
phoenicis-tests/src/main/java/org/phoenicis/tests/MockedRepository.java
phoenicis-tools/src/main/java/org/phoenicis/tools/version/Version.java
settings/POL_Formatter_Settings.xml

formatter: do not change line wraps

---

phoenicis-cli/src/main/java/org/phoenicis/cli/scriptui/ProgressUiFactoryCLI.java
phoenicis-cli/src/main/java/org/phoenicis/cli/scriptui/SetupUiFactoryCLI.java
phoenicis-cli/src/main/java/org/phoenicis/cli/scriptui/UiQuestionFactoryCLI.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/JavaFxUiConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/ProgressUiFactoryJavaFX.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/SetupUiFactoryJavaFX.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/UiQuestionFactoryJavaFX.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/ProgressUiFactory.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/SetupUiFactory.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/UiQuestionFactory.java

use safe beans for UI factories

---

phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java

unify logging for GitRepository

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/addrepository/ChooseRepositoryTypePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/addrepository/ClasspathRepositoryDetailsPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/addrepository/GitRepositoryDetailsPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/addrepository/LocalRepositoryDetailsPanel.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less

improve style of "add repository" dialogs

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less

use white background for icon list (except Breeze Dark)

---

i18n/fr.po

For some string I wasn't sure of the meaning, and while we won't be able to change the language used in POL5, I won't be able to verify.
But it's better thatn nothing :)

First version of fr.po

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationFilter.java

I'm not sure why I didn't do it like this originally?

Simplify ApplicationFilter

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindow.java

fixed: install wizard opens in background

---

phoenicis-cli/pom.xml
phoenicis-configuration/src/main/resources/log4j.properties
phoenicis-configuration/src/main/resources/logback.xml
phoenicis-javafx/pom.xml
pom.xml

use logback to write to logfile

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java

Fix category selection in application tab

---

phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java

fixes error log messages on startup

check if application.json and script.json exist when loading repository

---

phoenicis-configuration/src/main/resources/Linux.properties
phoenicis-configuration/src/main/resources/Mac OS X.properties
phoenicis-javafx/src/main/java/org/phoenicis/javafx/AppConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/settings/JavaFxSettingsController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSetting.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettings.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettingsConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettingsManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindow.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/UserInterfacePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
phoenicis-javafx/src/main/resources/javafx.properties
phoenicis-settings/src/main/java/org/phoenicis/settings/SettingsManager.java

implemented JavaFxSettingsManager

---

phoenicis-dist/src/deb/control/control

.deb: added openjfx dependency

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettingsManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/UserInterfacePanel.java

It's not really elaborate and requires a restart of Phoenicis but it will get you going if you messed up your settings completely.

added simple possibility to restore UI settings to default

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java
phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryConfiguration.java
phoenicis-settings/src/main/java/org/phoenicis/settings/SettingsManager.java

It's not really elaborate and requires a restart of Phoenicis but it will get you going if you messed up your settings completely.

added simple possibility to restore repository settings to default

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/AbstractContainerPanel.java

show container name in title of details view

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginePanel.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

use same style in all details views

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less

Dark Breeze theme: fixed toggle button style

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSetting.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettingsManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewsConfigurationLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftListWidgetChooser.java
phoenicis-javafx/src/main/resources/javafx.properties

remember list widget type selection

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindowView.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java

added documentation for MainWindowView

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/DummyListElement.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/compact/CompactListElement.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/details/DetailsListElement.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/icons/IconsListElement.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

fixed naming of style classes for list widgets

---

phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryException.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/ClasspathRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java

added RepositoryException

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/settings/SettingsController.java

something went wrong during the refactoring for JavaFxSettingsManager...

fixed name of SettingsController

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/SearchBox.java

Enhance searchbox with comments and Optional instances

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/DelayedFilterTextConsumer.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/SearchBox.java

And move `onSearch` and `onClear` callbacks to the `ApplicationSidebar` class

Add a new class DelayedFilterConsumer

---

phoenicis-configuration/src/main/resources/Linux.properties
phoenicis-configuration/src/main/resources/Mac OS X.properties
phoenicis-dist/src/scripts/phoenicis-cli.desktop
phoenicis-dist/src/scripts/phoenicis-javafx.desktop

also: changed application name to "Phoenicis PlayOnLinux/PlayOnMac"
fixes #713

added StartupNotify to .desktop files

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/FailurePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindowView.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java

set notification and failure reason whenever FailurePanel is shown
fixes #740

fixed handling of FailurePanel

---

phoenicis-javafx/pom.xml
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSetting.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettingsManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/resources/javafx.properties

implemented fuzzy search

---

phoenicis-javafx/src/main/resources/javafx.properties

added comments to javafx.properties

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/PhoenicisFilteredList.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftToggleGroup.java
phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/PhoenicisFilteredListTest.java

And readded the category filter to the Apps tab.
This PR fixes #985.
The new `PhoenicisFilteredList` currently has no tests, and therefore may still contain some bugs.

Added our own FilteredList class, called PhoenicisFilteredList

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java

fixed empty apps list if no search string provided

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/EditShortcutPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java

You can open the new panel to edit a shortcut by right-clicking an item in your library and then selecting "Edit" from the context menu.
fixes #1044

added possibility to change shortcut in shortcut details

---

phoenicis-dist/src/deb/control/control

added libxext6:i386 dependency for .deb

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

Unity theme: fixed label padding in sidebar

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

fixed height of sidebar buttons

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/EditShortcutPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java

added possibility to change shortcut miniature in JavaFX GUI

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/installations/ViewInstallations.java

deselect other installations when adding a new one

fixed: multiple installations selected

---

phoenicis-scripts/src/main/java/org/phoenicis/scripts/TriFunction.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/nashorn/builtins/SetupWizardInjector.java

unified setup wizards

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/AbstractFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/installations/InstallationsFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/installations/InstallationsSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/installations/ViewInstallations.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftToggleGroup.java

This PR fixes #1026.
Things left to do:
- Modify `EnginesFilter` to extend `AbstractFilter`

Refactor filters + add filters for Library and Installation tabs

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/AdhocList.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/ExpandedList.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/MappedList.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/PhoenicisFilteredList.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/PhoenicisTransformationList.java

added base class for ObservableLists

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationsView.java

Fixes #1085 and adds some additional JavaDoc.
The additional benefit of this change is, that the sorting is now performed only once and not with every filter change.

Change the order of the observable list operations in ApplicationView

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ErrorMessage.java

fixed JavaFX error message dialog size and set owner

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainersFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainersSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainersView.java

Add filter functionality for the containers tab

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSubCategoryTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesSidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesView.java

Change the implementation of EnginesFilter to extend AbstractFilter

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesSource.java

Tested with a renamed copy of Wine (in JS).
fixes #963

fixed callback for fetch engines

---

phoenicis-containers/src/main/java/org/phoenicis/containers/dto/ContainerDTO.java
phoenicis-containers/src/main/java/org/phoenicis/containers/dto/WinePrefixContainerDTO.java
phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EngineToolsManager.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanelFactory.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java

A new manager class for the engine tools which is agnostic of the specific engine.

implemented EngineToolsManager

---

phoenicis-containers/src/main/java/org/phoenicis/containers/ContainersConfiguration.java
phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerToolsTab.java

requires PhoenicisOrg/Scripts#395

use Wine tool to open terminal in prefix

---

phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ScriptDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/ClasspathRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java

enabled icons for scripts

---

phoenicis-library/src/main/java/org/phoenicis/library/LibraryManager.java
phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java
phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutDTO.java

The shortcut files cannot use the shortcut name because it might contain invalid characters (especially "/" as in "TRON RUN/r").
requires PhoenicisOrg/Scripts#413

added shortcut ID

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/ListWidgetEntry.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerInformationTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/EditShortcutPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryFilter.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryView.java
phoenicis-library/src/main/java/org/phoenicis/library/LibraryConfiguration.java
phoenicis-library/src/main/java/org/phoenicis/library/LibraryManager.java
phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java
phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutDTO.java
phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutInfoDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryConfiguration.java
phoenicis-tools/src/main/java/org/phoenicis/tools/ToolsConfiguration.java

fixes #1124 
requires PhoenicisOrg/Scripts#416

combine shortcut info in one json file

---

phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java

secure null icon/miniature when editing shortcut

---

phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java

check icon and miniature path for null when editing shortcut

---

i18n/de.po
i18n/fr.po
i18n/keys.pot

updated translation files

---

phoenicis-dist/src/scripts/phoenicis-cli

fixed phoenicis-cli script

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ApplicationDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/CategoryDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ScriptDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/dto/TypeDTO.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/ClasspathRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/MergeableRepository.java
phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/Repository.java

add context to executed scripts

---

phoenicis-tools/src/main/java/org/phoenicis/tools/config/CompatibleConfigFileFormat.java

do not log exception when container is created

---

phoenicis-repository/src/main/java/org/phoenicis/repository/FilesystemJsonRepositoryLocationLoader.java

Can't we use PhoenicisOrg instead of PlayOnLinux too ?

fixed default repositories (Fix #1155)

---

.travis.yml

Travis CI: test Linux and OSX

---

.travis.yml
check_formatted.sh
phoenicis-repository/src/main/java/org/phoenicis/repository/DefaultRepositoryManager.java

Travis CI: check that all files are formatted 

---

README.md

added Crowdin badge

---

.travis.yml
check_formatted.sh
phoenicis-javafx/src/main/java/org/phoenicis/javafx/UiMessageSenderJavaFXImplementation.java
pom.xml

Travis CI: do not run maven build for check format

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanelFactory.java

fixed container panel creation

---

docs/_pages/configuration.md
docs/_pages/home.md
docs/_pages/installation.md

Link to GitHub Pages documentation instead of wiki

---

.travis.yml
docs/_config.yml

Fix GitHub Pages configuration

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EngineTool.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EngineToolsManager.java

requires https://github.com/PhoenicisOrg/scripts/pull/575

Object oriented engine tools

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/Installer.java

Open issues: Aborting an installation does not work.
requires https://github.com/PhoenicisOrg/scripts/pull/577

Object oriented installers

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java

Fix "create shortcut"

---

phoenicis-configuration/src/main/resources/Linux.properties
phoenicis-configuration/src/main/resources/Mac OS X.properties

Fix Wine webservice URL

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/themes/Themes.java
phoenicis-javafx/src/main/resources/javafx.properties
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/mint-x/description.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/mint-x/main.less

Add Mint-X theme

---

phoenicis-containers/src/main/java/org/phoenicis/containers/GenericContainersManager.java

I have already merged the corresponding pr (#1275) for the 5.0-alpha branch to continue testing.

Fix shortcut deletion when container is deleted

---

phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java

I have already merged the corresponding pr (#1271) for the 5.0-alpha branch to continue testing.

Fix "Run executable" in container tools

---

docs/_data/navigation.yml
docs/_pages/release-process.md
docs/_pages/test-plan.md

Add test plan to docs

---

phoenicis-containers/pom.xml
phoenicis-containers/src/main/java/org/phoenicis/containers/ContainersConfiguration.java
phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java
phoenicis-engines/src/main/java/org/phoenicis/engines/Engine.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesConfiguration.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesManager.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesSource.java
phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineCategoryDTO.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesView.java

Use composition over inheritance for OOP engine implementation.
requires PhoenicisOrg/scripts#602

Implement OOP engines

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ConfirmMessage.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/UiQuestionFactoryJavaFX.java

Set owner for ConfirmMessage

---

i18n/keys.pot
pom.xml

Delete .pot timestamp

---

phoenicis-configuration/pom.xml

update only .pot, Crowdin will update the .po's

Do not update .po's during build

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/mint-x/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less

Themes: fix sidebar text colors

---

i18n/keys.pot
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerToolsTab.java

Unlock "run executable" button

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less

for now simply use the Wine icon
fixes #1269

Set button icon for engine installation

---

i18n/keys.pot
phoenicis-engines/src/main/java/org/phoenicis/engines/EngineSettingsManager.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSubCategoryTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesView.java

if engine is installed:
* disable "install" button
* enable "delete" button
if engine is **not** installed:
* enable "install" button
* disable "delete" button
fixes #1099

Check if engine is installed

---

i18n/keys.pot
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerToolsTab.java

open file chooser in container directory
fixes #1261

Update "run in container"

---

.travis.yml

Travis CI: test with OpenJDK 8

---

phoenicis-dist/src/scripts/phoenicis-cli
phoenicis-dist/src/scripts/phoenicis-javafx
phoenicis-dist/src/scripts/phoenicis.sh

Fix .deb package

---

phoenicis-cli/pom.xml
phoenicis-configuration/pom.xml
phoenicis-containers/pom.xml
phoenicis-dist/pom.xml
phoenicis-engines/pom.xml
phoenicis-entities/pom.xml
phoenicis-javafx/pom.xml
phoenicis-library/pom.xml
phoenicis-multithreading/pom.xml
phoenicis-repository/pom.xml
phoenicis-scripts/pom.xml
phoenicis-settings/pom.xml
phoenicis-tests/pom.xml
phoenicis-tools/pom.xml
phoenicis-win32/pom.xml
pom.xml

define phoenicis.version in the top level pom
fixes #1371

Use one version variable

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/JavaFXApplication.java

avoid that application fails silently

Catch launch error

---

.travis.yml
i18n/keys.pot
phoenicis-javafx/pom.xml
phoenicis-multithreading/pom.xml
phoenicis-tools/pom.xml
pom.xml

Add support for JDK 11

---

phoenicis-repository/src/main/java/org/phoenicis/repository/types/GitRepository.java

Prevent cloning git repository from different threads in parallel

---

.travis.yml

fix failing build on master: the target system for the .deb is Ubuntu 18.04 (latest LTS)

Travis: test .deb on Ubuntu 18.04

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/PhoenicisFilteredList.java

This PR removes the dependencies to `com.sun.javafx.collections` from inside the `PhoenicisFilteredList` class and fixes #1472.
Please be sure to test it locally first before we merge it, it is working correctly for me but just to be sure...

Remove the dependencies to com.sun.javafx.collections

---

phoenicis-dist/src/scripts/phoenicis-java8.sh
phoenicis-dist/src/scripts/phoenicis.sh

Provide phoenicis.sh for Java 8 and Java 10+

---

docs/_docs/Users/build.md

Update build documentation for Ubuntu 18.04/18.10

---

.travis.yml
pom.xml

Revert workaround for surefire bug 1588

---

.travis.yml

Travis: add stage to build and test packages

---

.travis.yml

The stage works but the output shows:
```
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```

Travis: fix .deb installation

---

phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java

fixes #1402 (test creates an empty git folder)

Run AppConfigurationInitialisationTest in a temporary application.user.root

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerInformationTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanel.java

A simple button on the container info tab.
fixes #1441

Add button to open container in file browser

---

phoenicis-javafx/pom.xml

Exclude .less files from .jar

---

phoenicis-javafx/src/main/java/module-info.java

Fix: BreezeDark icons missing

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ErrorMessage.java

Fix small error message

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/behavior/BehaviorBase.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/control/ControlBase.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/skin/BehaviorSkinBase.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/skin/SkinBase.java

Improve the base classes for custom components

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesFilter.java

Fixes #1562.
This PR is part of #1536

Fix the engines filter

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/skin/SidebarGroupSkin.java

Fixes #1560.
This PR is part of #1536

Fix sidebar group bug

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesConfiguration.java
phoenicis-engines/src/main/java/org/phoenicis/engines/Verb.java
phoenicis-engines/src/main/java/org/phoenicis/engines/VerbsManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerVerbsTab.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/InstallationType.java

fixes https://github.com/PhoenicisOrg/scripts/issues/534

Implement OOP Verbs

---

phoenicis-repository/src/main/java/org/phoenicis/repository/types/GitRepository.java

Currently, fetching a git repository fails if the local git repository cannot be updated. Therefore it is not possible to use the local checkout e.g. if you're not connected to the Internet.
This pull request changes this behavior such that only a warning is printed if the local git repository cannot be updated.
fixes #1548

Do not fail if local git repository cannot be updated

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java

Create default engine icons css in FX thread

---

phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java

Shortcut creation: use fallback miniature/icon if miniature/icon cannot be accessed

---

docs/_docs/Developers/release-process.md

use pattern for protected branches

Update release process documentation

---

phoenicis-configuration/src/main/resources/logback.xml

Set default log level to INFO

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java

This PR closes #1623.
In addition because the `ConfirmDialog` sets its message inside the content section and not the header section the dialog now looks slightly different.

Replace Alert by ConfirmDialog

---

.travis.yml

Travis: install flatpak-builder

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerToolsTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/CreateShortcutPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/EditShortcutPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/addrepository/ChooseRepositoryTypePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/addrepository/LocalRepositoryDetailsPanel.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/UiSetupWizardImplementation.java
phoenicis-tools/src/main/java/org/phoenicis/tools/checksum/ChecksumCalculator.java

https://github.com/PhoenicisOrg/phoenicis/issues/1466

No space before ellipsis

---

.travis.yml

Travis: do not build with OpenJDK 8

---

pom.xml

Fix Maven compiler version

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerInformationTab.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanel.java

Rename "prefix" to "container"

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/dialogs/InformationDialog.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java

Show "please restart" dialog after repository reset to default

---

phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.appdata.xml

Flatpak appdata.xml: add help URL

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryView.java

Use StringUtils.capitalize when creating shortcut

---

phoenicis-containers/src/main/java/module-info.java
phoenicis-containers/src/main/java/org/phoenicis/containers/GenericContainersManager.java
phoenicis-javafx/src/main/java/module-info.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-library/src/main/java/module-info.java
phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java
phoenicis-library/src/main/java/org/phoenicis/library/ShortcutRunner.java
phoenicis-scripts/src/main/java/module-info.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/nashorn/builtins/IncludeInjector.java
pom.xml

Note that the PR is not towards master but a feature branch so that we can work together and share our progress whenever someone figures anything out.
Next topic that must be tackled is the "include" function.

First steps

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/themes/ClasspathTheme.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/themes/Theme.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/themes/ThemeManager.java

This PR changes the themes to allow for them to contain multiple css files which are then loaded in a predefined order.
This PR is relevant for #1800.

Allow for multiple file themes

---

docs/_docs/Developers/build.md

Fix OpenJDK 11 download link in build documentation

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/control/TabIndicator.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/skin/TabIndicatorSkin.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/installations/InstallationsView.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/standard/main.less

This PR closes #1786 by implementing a `TabIndicator` component, which informs the user about changes to a tab, which occurred in the time interval since the user visited the tab the last time.
Screenshots:

Add a new TabIndicator component to inform the user about changes

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/setting/skin/UserInterfacePanelSkin.java

This PR fixes a bug where the theme name is displayed wrong the settings.

Fix theme name display bug

---

docs/_docs/Developers/coding-rules.md

Developer documentation: add coding rules

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/control/LibraryFeaturePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/control/LibrarySidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/LibraryFeaturePanelSkin.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/ShortcutEditingPanelSkin.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/utils/LibraryDetailsPanelType.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/utils/LibraryDetailsPanels.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewsConfigurationLibrary.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/MainWindow.java

This PR refactors the `LibraryView` class with MVC in mind. For this the `LibraryView` class has been replaced by a `LibraryFeaturePanel` component.

Refactor the LibraryView class with MVC in mind

---

docs/_docs/Developers/script-interaction.md

This PR adds the interface communication approach discussed in #1882 to the documentation

Add interface communication approach to documentation

---

docs/_docs/Developers/intellij-idea.md
phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml

Docs: do not set nashorn compat on command line

---

phoenicis-repository/src/main/java/org/phoenicis/repository/DefaultRepositoryManager.java

- callbacks should not be iterated while a new callback is added
- new repositories should not be added concurrently

Avoid concurrent modification of DefaultRepositoryManager

---

.gitpod.dockerfile

Avoid that changes in Java minor versions break Gitpod.
fixes #1941

Fix Gitpod

---

pom.xml

Update jackson-databind to 2.9.9

---

.travis.yml
phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml

- add OpenJDK 11
- remove Oracle JDK support
- use OpenJDK 12 for Flatpak
see #1960

Travis: build with JDK 12

---

.travis.yml
phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml

until OpenJDK 12 is fully tested

Flatpak: use OpenJDK 11

---

docs/_docs/Developers/intellij-idea.md

Improve IntelliJ IDEA configuration documentation

---

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less

Breeze Dark: Fix repository table colors

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/JavaFXApplication.java

There's nothing useful we could do about the exception at this point anyways.
fixes #1956

Catch exceptions when closing the JavaFX application

---

phoenicis-dist/src/scripts/phoenicis-create-package.sh

Needs https://github.com/PhoenicisOrg/phoenicis-winebuild/pull/98 and https://github.com/PhoenicisOrg/scripts/pull/1019.

Remove libncurses, libfreetype, libbsd0 from .deb and add libc6:i386

---

phoenicis-containers/src/main/java/org/phoenicis/containers/ContainersConfiguration.java
phoenicis-containers/src/main/java/org/phoenicis/containers/GenericContainersManager.java
phoenicis-repository/src/main/java/org/phoenicis/repository/DefaultRepositoryManager.java
phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryConfiguration.java
phoenicis-repository/src/main/java/org/phoenicis/repository/location/ClasspathRepositoryLocation.java
phoenicis-repository/src/main/java/org/phoenicis/repository/location/GitRepositoryLocation.java
phoenicis-repository/src/main/java/org/phoenicis/repository/location/LocalRepositoryLocation.java
phoenicis-repository/src/main/java/org/phoenicis/repository/location/RepositoryLocation.java
phoenicis-repository/src/main/java/org/phoenicis/repository/types/GitRepository.java
phoenicis-tools/src/main/java/org/phoenicis/tools/files/FileUtilities.java
phoenicis-tools/src/main/java/org/phoenicis/tools/files/FilesManipulator.java

This PR refactors the `FileUtilities` class. This contains a change to the method signatures to accept Strings instead of File objects. In addition some additional file access methods are now forwarded from JS to Java to make the accessibility-split more clean.

Refactor the "FileUtilities" Class

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EngineSettingsManager.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesConfiguration.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java

This PR is the Java counterpart to PhoenicisOrg/scripts#1016.
Please be aware that I couldn't fully test this PR, because the settings are all loaded at once during application startup. This means that it is only possible to test this PR if all setting implementations are changed to the new syntax.

Simplify the Setting Scripts

---

phoenicis-engines/src/main/java/org/phoenicis/engines/Verb.java
phoenicis-engines/src/main/java/org/phoenicis/engines/VerbsManager.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java

This PR is the Java counterpart to https://github.com/PhoenicisOrg/scripts/pull/1015.
Additionally I've slightly modified the `Verb` interface to indicate that a `ScriptException` can be thrown from inside. Strangely I wasn't able to catch the `InterruptedException` which is thrown when an installer script is canceled...

Simplify the Verb Scripts

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EngineToolsManager.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java

This PR is the Java counterpart to PhoenicisOrg/scripts#1017.

Simplify the Tool Scripts

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesManager.java
phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java

This PR is the Java counterpart to PhoenicisOrg/scripts#1018.

Simplify the Engine Scripts

---

phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesConfiguration.java
phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesManager.java

This PR fixes a bug during engine fetching that leads to an empty engine list after application startup

Fix a Bug during Engine Fetching

---

phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/UiSetupWizardImplementation.java

fixes https://github.com/PhoenicisOrg/scripts/issues/1054

Fix wizard browse step

---

phoenicis-dist/src/scripts/phoenicis-create-package.sh

Add java.management to packaging script

---

phoenicis-containers/src/main/java/org/phoenicis/containers/GenericContainersManager.java

Do not show hidden directories in containers tab

---

phoenicis-configuration/pom.xml

`slf4j` is required by `Localisation`

Remove unused jgettext dependency

---

.travis.yml

Travis: also build with OpenJDK 13

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/skin/ContainerEngineSettingsPanelSkin.java

Avoid exception if engine setting cannot be fetched

---

phoenicis-dist/src/flatpak/distribution.xml
phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml

Fix flatpak

---

phoenicis-javafx/pom.xml
phoenicis-tools/pom.xml

This PR updates the versions of:
- update version of jmimemagic
- update version of javafx-collections
This PR should fix #1990 @ImperatorS79 @Zemogiter could you please give this a test?

Update PhoenicisOrg dependencies

---

docs/_docs/Developers/intellij-idea.md
docs/_docs/Developers/maven-modules.md
phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
phoenicis-dist/src/scripts/phoenicis-create-package-java12.sh
phoenicis-dist/src/scripts/phoenicis-create-package.sh

fixes #2038
I'm not sure about https://github.com/PhoenicisOrg/phoenicis/blob/730a6b85b0743bc2cfc393904bd12e711ec0cdd6/phoenicis-tests/src/main/java/org/phoenicis/tests/PhoenicisTestsApp.java#L70.

Remove remaining Nashorn stuff

---

phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java

Ignore AppConfigurationInitialisationTest

---

phoenicis-javafx/pom.xml

Update javafx-collections to 1.2.5

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/control/LibraryFeaturePanel.java

Fix shortcut creation in library tab

---

phoenicis-repository/src/main/java/org/phoenicis/repository/types/GitRepository.java

This PR improves the logging information for `GitRepository`

Improve the logging information for "GitRepository"

---

phoenicis-dist/src/resources/Phoenicis.desktop

Fix missing window frame (e.g. on Elementary OS)

---

docs/_docs/Developers/test-plan.md
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/control/LibrarySidebar.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/control/ShortcutInformationPanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/LibraryFeaturePanelSkin.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/LibrarySidebarSkin.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/ShortcutInformationPanelSkin.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/setting/control/UserInterfacePanel.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/setting/skin/UserInterfacePanelSkin.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSetting.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettingsManager.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/SettingsView.java
phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/MainWindow.java
phoenicis-javafx/src/main/resources/org/phoenicis/javafx/javafx.properties

JavaFX: simple/advanced mode

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/MainWindow.java

Simple mode: switch to installations tab

---

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java

Remove confirmation dialog to close Phoenicis

---

.github/workflows/update-translations.yml
i18n/keys.pot

The action is not allowed to push to protected branches (master).

Update translations on all branches

---

.github/workflows/ci.yml
.github/workflows/dependabot.yml
.github/workflows/linter.yml
.github/workflows/update-translations.yml
i18n/keys.pot

otherwise they do not run for PRs from forks

Run GitHub actions for PRs

---

.github/workflows/dependabot.yml

see https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60

Fix dependabot auto merge action

---

phoenicis-configuration/src/test/java/org/phoenicis/configuration/localisation/LocalisationTest.java
phoenicis-multithreading/src/test/java/org/phoenicis/multithreading/ControlledThreadPoolExecutorServiceCloserTest.java
phoenicis-tools/src/test/java/org/phoenicis/tools/files/DirectoryWatcherFilesTest.java

Fix build after Mockito update

---

pom.xml

Fix build after buildnumber-maven-plugin update

---

.github/workflows/ci.yml

CI: do not upload Mac OS artifacts

---

.github/dependabot.yml
pom.xml

fixes https://github.com/PhoenicisOrg/scripts/issues/1256

Pin GraalVM to 21.1.x

---

.github/dependabot.yml
pom.xml

fixes https://github.com/PhoenicisOrg/scripts/issues/1256

Pin GraalVM to 21.1.x (2nd try)

---

.github/workflows/ci.yml

CI: fix Java 15 build

---

.github/workflows/ci.yml

CI: fix Flatpak build

---

.github/workflows/linter.yml

- fix job name (showed only "run" in branch protection rules)
- use setup-java v3

Update linter action
