PhoenicisOrg/phoenicis

src/main/resources/playonlinux.properties
The missing property-key "webservice.url" causes a `NullPointerException` for me on Linux (since an empty `rawProperty` is passed to `pattern.matcher()`). Since this key is present in the `playonmac.properties` file, I figured this would be a suitable fix.
=> Fix NullPointerException in Linux during startup.

src/main/python/SetupWindow/SetupWindowManager.py, src/main/python/SetupWindow/SetupWindowNetcatCommandParser.py, src/main/python/SetupWindow/SetupWindowNetcatServer.py, src/main/python/v4wrapper.py
Using the `Tools\Running a local Script` function, I am constantly getting ErrorMessages like:
```
Exception in thread "Thread-7" SyntaxError: Non-ASCII character in file '/mnt/coding/Java/PlayOnLinux/POL-POM-5/src/main/python/v4wrapper.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
This is a possible fix for that. But I am not too familiar with python, so that might be the wrong approach.
=> Added magic comment for encoding in python scripts.

src/main/java/com/playonlinux/domain/Script.java, src/test/java/com/playonlinux/domain/LegacyWrapperTest.java, src/test/resources/com/playonlinux/domain/wrapperTestScript.sh
I now implemented a TestCase which is running a LegacyScript creating a temporary file and checking if that file exists afterwards. The way I used the PythonInterpreter here is somewhat ugly. Maybe we should create a static HelperClass for instantiating and setting up PythonInterpreters?
=> Implemented TestCase for the LegacyScript-Wrapper.

src/main/bash/lib/sources
Fixed small typo which caused that the `bash/lib/scripts` - script could not be found.
=> Fix small Typo resolving FileNotFound issue.

src/main/java/com/playonlinux/ui/impl/javafx/installwindow/InstallWindow.java
I'm reverting it because I haven't seen that there is a small thing to fix. The GUI will actually have also a miniature. So we cannot really dock the Webkit widget to the right.
Here is the same window for PlayOnLinux v4 
Reverts PlayOnLinux/POL-POM-5#19
=> Revert "Rewrote InstallWindow's mainScene with automatic sizing."

src/main/java/com/playonlinux/services/RemoteAvailableInstallersPlayOnLinuxImplementation.java, src/main/java/com/playonlinux/ui/api/InstallerFilter.java, src/main/java/com/playonlinux/ui/api/RemoteAvailableInstallers.java, src/main/java/com/playonlinux/ui/impl/javafx/installwindow/AvailableInstallerListWidget.java, src/main/java/com/playonlinux/ui/impl/javafx/installwindow/InstallWindow.java, src/main/java/com/playonlinux/ui/impl/javafx/installwindow/InstallWindowEventHandler.java
I've refactored the filtering for Installer-Scripts displayed in the InstallWindow.
This is a fix for #24.
Abstract:
I created a class (InstallerFilter) which handles all filter parameters as well as the filtering itself. This extracts the filter-logic out of the View-Part (AvailableInstallerList) and gives us a central point where we can easily change this behavior or add new parameters. InstallerFilter is an Observable, automatically notifying observers (the AvailableInstallerList) that the filter-parameters have changed, causing a refiltering and a UI refresh.
=> Refactor the Filtering of Installers

src/main/java/com/playonlinux/common/api/Disposable.java
The `dispose()` method adds the functionality for directly telling a class to clean itself up if necessary.
This is the point where resources like streams should be closed.
=> Create an interface for classes that need instant cleanup.

pom.xml, src/main/java/com/playonlinux/app/PlayOnLinuxConfig.java, src/main/java/com/playonlinux/domain/Localisation.java, src/main/java/com/playonlinux/domain/lang/CatalogLanguageBundle.java, src/main/java/com/playonlinux/domain/lang/FallbackLanguageBundle.java, src/main/java/com/playonlinux/domain/lang/LanguageBundle.java, src/main/java/com/playonlinux/domain/lang/LanguageBundleSelector.java, src/test/java/com/playonlinux/domain/lang/LanguageBundleSelectorTest.java, src/test/java/com/playonlinux/framework/SetupWizardTest.java
Not entirely happy with injecting a static field but the basic implementation is there. Tested with German language in the existing interface.
- I'm not sure how to handle the zh_CN ; zh_TW pair since neither specify the top-level zh language.
- en_GB also isn't used as default but instead strings aren't translated as fallback, is this okay?
=> Use PO files for translation like gettext

src/main/java/com/playonlinux/common/api/filter/Filter.java, src/main/java/com/playonlinux/common/api/filter/Filterable.java, src/main/java/com/playonlinux/common/api/list/ObservableList.java, src/main/java/com/playonlinux/common/api/services/RemoteAvailableInstallers.java, src/main/java/com/playonlinux/common/filter/CenterItemFilter.java, src/main/java/com/playonlinux/common/list/FilterPromise.java, src/main/java/com/playonlinux/common/list/FilterableList.java, src/main/java/com/playonlinux/common/list/ObservableArrayList.java, src/main/java/com/playonlinux/common/services/RemoteAvailableInstallersPlayOnLinuxImplementation.java, src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/center/CategoryView.java, src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/center/ViewApps.java
Refactored the process of filtering, which then can easily be applied for the other sections (Shortcuts, Engine-Versions, ...).
We should talk about how and where to handle the flag-filtering (testing / NoCd / Commercial) - which I left unimplemented for now.
__Abstract__:
`Filter<T>` and `Filterable<T>` are both observable. Whenever something changes (e.g. filter-parameters), the observers are notified.
I combined both within `FilterPromise<T>`, which listens to Filter and Filterable and updates, after either one of them changed - directly providing the new filtered list.
I outsourced the list of categories into an own widget (`CategoryView`) to avoid unnecessary repaints and potential memory leaks. The CategoryView is passed an `ObservableList<T>` which fires an update after its list …
=> Refactor filtering Version 3

src/main/java/com/playonlinux/common/api/services/InstalledApplications.java, src/main/java/com/playonlinux/common/dto/ui/InstalledApplicationDTO.java, src/main/java/com/playonlinux/common/filter/InstalledApplicationFilter.java, src/main/java/com/playonlinux/common/services/InstalledApplicationsPlayOnLinuxImplementation.java, src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/apps/ViewApps.java, src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/library/ApplicationListWidget.java, src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/library/ViewLibrary.java, src/test/java/com/playonlinux/common/dto/InstalledApplicationDTOTest.java
MainWindow search bar now has filtering applied to it:
* Rename ShortcutDTO to InstalledApplicationDTO for better clarification.
* Create a new filter for InstalledApplicationDTO.
* Make ApplicationListWidget apply the new filter for user keypress events on the shown data.
Notes:
* Left the filter apply() so that it would show all applications on start unlike it is done in ViewApps.
* ApplicationListWidget update() is called twice on startup. I was not able to tacle the problem but it is currently in the main branch too. Could use some looking into.
=> Main window search

src/main/java/com/playonlinux/ui/common/CommandHistory.java, src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/console/CommandHistory.java, src/main/java/com/playonlinux/ui/impl/javafx/mainwindow/console/ConsoleTab.java, src/test/java/com/playonlinux/ui/common/CommandHistoryTest.java
The History is now handled in the small helper class `CommandHistory`.
Now not only the command itself, but also the cursorPosition when hitting enter is saved and restored.
The `CommandHistory` helper should probably be moved out of impl.javafx, since it can at least be shared with the gtk gui.
=> Outsourcing History and saving cursorPosition.

pom.xml
Make sure both dependencies get installed when executing mvn clean. Before, only the qtjambi dependency would be installed.
=> Fix for external dependencies installation in mvn clean goal

phoenicis-qt/src/main/java/com/playonlinux/qt/mainwindow/MainWindowEventHandler.java
Add a fileExtension-filter to the dialog for running local scripts.
=> [Qt] Add File-Extension filter to runLocalScript-dialog

phoenicis-javafx/src/main/java/com/playonlinux/javafx/setupwindow/StepRepresentationBrowse.java
The next-button is now enabled when the user first selects a valid file from the dialog.
Canceling the dialog does not reset the before chosen file.
=> [JavaFX] Fix BrowseStep next-button always enabled

phoenicis-core/src/main/java/com/playonlinux/apps/AppsEntitiesProvider.java, phoenicis-core/src/main/java/com/playonlinux/apps/DefaultAppsManager.java, phoenicis-core/src/main/java/com/playonlinux/apps/DefaultInstallerDownloaderEntityProvider.java, phoenicis-core/src/main/java/com/playonlinux/core/entities/ProgressEntity.java, phoenicis-core/src/main/java/com/playonlinux/core/entities/ProgressState.java, phoenicis-core/src/main/java/com/playonlinux/core/utils/ChecksumCalculator.java, phoenicis-core/src/main/java/com/playonlinux/core/utils/archive/Extractor.java, phoenicis-core/src/main/java/com/playonlinux/core/utils/archive/Tar.java, phoenicis-core/src/main/java/com/playonlinux/core/webservice/DownloadEnvelope.java, phoenicis-core/src/main/java/com/playonlinux/core/webservice/HTTPDownloader.java, phoenicis-core/src/main/java/com/playonlinux/core/webservice/Webservice.java, phoenicis-core/src/main/java/com/playonlinux/engines/wine/DefaultWineVersionsManager.java, phoenicis-core/src/main/java/com/playonlinux/engines/wine/packages/WinePackageProvider.java, phoenicis-core/src/main/java/com/playonlinux/framework/Checksum.java, phoenicis-core/src/main/java/com/playonlinux/framework/Downloader.java, phoenicis-core/src/main/java/com/playonlinux/ui/api/ProgressControl.java, phoenicis-javafx/src/main/java/com/playonlinux/javafx/setupwindow/StepRepresentationProgressBar.java
Use consumer instead of observer in HTTPDownloader.
It has impact on ProgressStateEntity and classes using it. ProgressStateEntity was renamed ProgressEntity and internal enum state was externalized in ProgressState.
=> HTTPDownloader as Consumer

phoenicis-core/pom.xml, pom.xml, sonar-project.properties
- Corrected build to generate coverage reports.
- Updated Jacoco Version.
- Added a sonar-project.properties as SonarQube maven builder is deprecated.
=> Sonar properties

phoenicis-dist/src/scripts/PlayOnLinux.sh
- Ensure path of Java 8 takes precedence on systems with Java 7 and 8 both installed
- This is non-destructive and does not force users to set the default java env to Java
=> Ensure we are running Java 8

phoenicis-dist/src/assembly/distribution.xml
[WARNING] The assembly descriptor contains a filesystem-root relative
reference, which is not cross platform compatible /
=> fixed outputDirectory of assembly

README.md
Replaced the outdated build instructions with a link to the correct build instructions in the GitHub wiki.
=> Updated build instructions in README.md

phoenicis-dist/src/scripts/PlayOnLinux.sh
Should be up to users to set their default java version
on Arch Linux, you could use the below to hotswap OpenJDK and Oracle JDK, but I haven't rigged it yet to be distro-agnostic
```
#!/bin/bash
POL_HOME=/opt/playonlinux5
CLASSPATH=${CLASSPATH}:$POL_HOME/lib/*
if [[ $(archlinux-java get | cut -d "-" -f2) >= 8 ]]; then
export JAVA_HOME=$(archlinux-java get)
else
export JAVA_HOME=$(ls /usr/lib/jvm/java-{8,9}-*/bin/javac 2>/dev/null | cut -d "/" -f-5 | head -1)
fi
java -classpath "$CLASSPATH" com.playonlinux.javafx.JavaFXApplication "$@"
```
=> No need for hacky workaround with java 8 path

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/common/widget/MiniatureListWidget.java
The size of the app list is now adjusted with the window size.
small window:
wide window:
=> size app list with window size

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/common/widget/MiniatureListWidget.java
Fixes: Long game titles get shown incorrectly #431
- show tooltip when hovering app (might be wrapped)
- truncate app name if necessary
=> Fixed problems with long app names

phoenicis-javafx/src/main/java/com/playonlinux/javafx/views/mainwindow/apps/AppPanel.java
It doesn't make sense to use the MiniatureListWidget.Element because
- there is no text
- there is no tooltip
- you cannot click it, so hover is useless
- the hover highlight looks strange because it also highlights the part where the text would be usually
=> use plain image for app description

phoenicis-tools/src/main/java/com/playonlinux/tools/system/ArchitectureFetcher.java
The property os.arch returns i386 and not x86 on 32bit Ubuntu (and possibly other Linux flavours).
Here is a screenshot to prove this:
fixes #426 
(The screenshot and tests were done on Ubuntu 16.04 32bit)
=> Add i386 as possible value for property os.arch (fixes #426)

phoenicis-dist/pom.xml, phoenicis-dist/src/deb/control/control
see #551 
Just a first approach, still with several issues:
- uses phoenicis-dist, probably better in top level pom?
- installs to /usr/shar, should be split to /usr/local/lib and /usr/local/bin
- PlayOnLinux.sh is not executable after installation
- control file needs to be improved
=> first approach to create .deb

README.md
If you don't like having a link in the heading then just use the old format but fix it so it reads `[Wiki:Build](https://github.com/Phoenicis/POL-POM-5/wiki/Build)`
Also not sure why Code Quality is a lesser heading to Building (but haven't included that in the pull).
=> Fixed link to building and simplified it

phoenicis-apps/src/main/java/org/phoenicis/apps/TeeApplicationsSource.java
Arrays cannot be used in a Set because they use the default hashCode() implementation. Therefore, every array object has a unique hash even if the content is the same as in another array.
fixes #398
=> fixed duplicate miniatures

phoenicis-containers/src/main/java/org/phoenicis/containers/ContainersConfiguration.java, phoenicis-containers/src/main/java/org/phoenicis/containers/dto/WinePrefixContainerDTO.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainersManager.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/configurations/DefaultWinePrefixContainerDisplayConfiguration.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/configurations/DefaultWinePrefixContainerInputConfiguration.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/configurations/RegistryWinePrefixContainerDisplayConfiguration.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/configurations/RegistryWinePrefixContainerInputConfiguration.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/configurations/WinePrefixContainerDisplayConfiguration.java, phoenicis-containers/src/main/java/org/phoenicis/containers/wine/configurations/WinePrefixContainerInputConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java
=> use wording "WinePrefixContainer*"

phoenicis-engines/src/main/java/org/phoenicis/engines/CombinedEnginesFilter.java, phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesConfiguration.java, phoenicis-engines/src/main/java/org/phoenicis/engines/EnginesSource.java, phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineCategoryDTO.java, phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineDTO.java, phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineSubCategoryDTO.java, phoenicis-engines/src/main/java/org/phoenicis/engines/dto/EngineVersionDTO.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginePanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/ProgressUiJavaFXImplementation.java
Preparation for a generic engine handling as described in #620. 
Includes a generic install/delete.
- fixes #614
- fixes #615
- requires PlayOnLinux/Scripts#175
The EngineVersionDTO is not yet generic. It should contain an engine specific userData Map like EngineDTO. However, this requires a change in the Wine JSON format (Wine specific information like Mono/Gecko file should be contained in userData).
=> prepared generic engines (including install/delete)

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/StepRepresentationMenu.java
This disables the next button if the default is empty and enables it if a selection is made.
Used in PlayOnLinux/Scripts#177
I used the formatter and cleanup settings from the readme. It still changed stuff I did not touch.
=> disable next button if the menu selection is empty

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css
This should fix issue #634.
What I don't understand is, why `-fx-fill: #FFFFFF;` doesn't change the text color to white for the dark theme, because at least in my eyes it works for the Breeze Dark theme (`-fx-fill: #bdc3c7;`)
=> Fixing #634

pom.xml
This PR targets Issue #642 fixes the error messages visible in eclipse, that say:
> Plugin execution not covered by lifecycle configuration: com.googlecode.maven-java-formatter-plugin:maven-java-formatter-plugin:0.4:format (execution: default, phase: process-  sources)
The fix is done by removing the execution goal. Is this goal really needed? Running `mvn java-formatter:format` seems to format the code (at least I see a lot of skips because everything is formatted).
In addition I saw that we're using quite an old version of the maven-java-formatter plugin, does this have a reason?
The newest version seems to be 2.0.0 - 2.0.1 (as per https://github.com/revelc/formatter-maven-plugin).
=> Fixing eclipse error message in pom files for the maven-java-formatter-plugin

phoenicis-apps/src/main/java/org/phoenicis/apps/MergeableApplicationsSource.java, phoenicis-apps/src/main/java/org/phoenicis/apps/MultipleApplicationsSource.java, phoenicis-apps/src/main/java/org/phoenicis/apps/TeeApplicationsSource.java
This PR changes the implementation of MultipleApplicationsSource to be parallel through the use of the Java 8 Streaming API, see also #650. 
In addition this PR extracts the merging functionality of two `CategoryDTOs` from the `TeeApplicationsSource` class to a new interface called `MergeableApplicationsSource`, which enables this functionally to be directly used in `MultipleApplicationsSource`.
=> Changing the implementation of MultipleApplicationsSource to be parallel

phoenicis-apps/src/main/java/org/phoenicis/apps/GitApplicationsSource.java, phoenicis-apps/src/main/java/org/phoenicis/apps/LocalApplicationsSource.java, phoenicis-apps/src/main/java/org/phoenicis/apps/dto/ScriptDTO.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/settings/SettingsController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java, phoenicis-settings/src/main/java/org/phoenicis/settings/Setting.java, phoenicis-settings/src/main/java/org/phoenicis/settings/SettingsManager.java
This PR adds source information to the scripts in the GUI, according to #656:
While doing this, I've also removed the cache variable from `GitApplicationsSource`, because we're using `CachedApplicationsSource` for caching purposes.
=> Added source information for scripts in the GUI

phoenicis-configuration/src/main/resources/Linux.properties, phoenicis-configuration/src/main/resources/Mac OS X.properties
Added the missing default value for the new `viewsource` property.
See the comments on commit 4b08e122ae034459e614939d398a2f4a6a774387 for details.
=> Bugfix: Added missing default values for the viewsources property

phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java
This PR should temporarily solve #673 by ignoring the configuration test. This test should be included again at the time when the textfx team releases their next version 4.0.6-alpha.
It would be nice if someone with the problem described in #673 could test this PR.
=> Set the javafx configuration test as ignored

phoenicis-javafx/pom.xml, phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java
This PR updates testfx to version `4.0.6-alpha` and reinserts the configuration initialisation test. This should fix #673.
=> Reinsert the configuration initialisation test

phoenicis-apps/src/main/java/org/phoenicis/apps/AppsConfiguration.java, phoenicis-apps/src/main/java/org/phoenicis/apps/BackgroundRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/CachedRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/ClasspathRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/ConfigurableRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/FilterRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/GitRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/LocalRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/MultipleRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/RepositoryManager.java, phoenicis-apps/src/main/java/org/phoenicis/apps/TeeRepository.java, phoenicis-javafx/pom.xml, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ExpandedList.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/MappedList.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widget/MiniatureListWidget.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/DragableRepositoryListCell.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftToggleGroup.java, phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/ExpandedListTest.java, phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/MappedListTest.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/ScriptsConfiguration.java
This PR enables POL 5 to process the following repository changes in the repository settings at runtime:
- The addition of a new repository through the "Add" button
- The removal of one or more repositories through the "Remove" button
- The permutation of two repositories through drag and drop
In addition this PR removes the `EasyBind` dependency again, because it doesn't remember its mappings. If you remove an element from the source list it creates a new mapping for the removed element and forwards it to its own bindings to be removed. Because the new mapping and the old mappings don't need to be equal (like for the category-`ToggleButton`s as an example), it's impossible to remove the old elements because they are not equal to the to be deleted ones.
The new `MappedList` implementation …
=> Add repository manager

phoenicis-tests/src/main/java/org/phoenicis/tests/PhoenicisTestsConfiguration.java
This PR updates a missed `appsConfiguration.repository()` method call, from PR #688.
I'm not sure how I missed this, because I did run `mvn test` before/after pushing my commits, which, as far as I remember, did result in a `BUILD SUCCESS`....
=> Fixing repository query call in PhoenixisTestsConfiguration

phoenicis-apps/src/main/java/org/phoenicis/apps/MultipleRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/RepositoryManager.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java
This PR changes the priority of new repositories. 
Previously a new repository were added as the repository with the lowest priority, now they get the highest priority.
In addition this PR fixes a bug, that the repository order wasn't saved to disk after the order has been changed.
The current implementation (including the introduced changes in this PR) of the `MultipleRepository` and the `TeeRepository` contradict the information of the Repository page in the wiki, because currently it seems like the most important repository is at the beginning of the list and not at the end.
This behavior already existed before PR #657, which modified both `MultipleRepository` and `TeeRepository`. The root cause for this is line 92 in `MergeableRepository` where the parameters in the …
=> New repositories are now added as the ones with the highest priority

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/AbstractContainerPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanelFactory.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java
This PR adds a ComboBox to the information tab in the `WinePrefixContainerPanel`, that enables the user to change the engine version of an existing container.
After opening the container details the engine version ComboBox will automatically show the currently selected engine version.
**This PR is currently only a proof of concept and shouldn't be merged, because it is incomplete and has a few design problems in my eyes!**
For more information see #625.
=> Make the engine version of a container changeable

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java
When running `mvn clean test` on the master branch I get:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project phoenicis-javafx: Compilation failure
[ERROR] /home/marc/Dokumente/Play on Linux/POL-POM-5/phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java:[21,40] package com.sun.xml.internal.ws.api.pipe does not exist
```
This PR should fix this.
=> Fixed a bug that a dependency couldn't be found

phoenicis-apps/src/main/java/org/phoenicis/apps/AppsConfiguration.java, phoenicis-apps/src/main/java/org/phoenicis/apps/DefaultRepositoryManager.java, phoenicis-apps/src/main/java/org/phoenicis/apps/NullRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/RepositoryManager.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/ScriptsConfiguration.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/interpreter/ScriptFetcher.java, phoenicis-tests/src/main/java/org/phoenicis/tests/PhoenicisTestsConfiguration.java
This PR removes the access to the `CacheRepository` in the `RepositoryManager` from outside.
This is needed, because we can't be sure that the repository structure of POL 5 will look like it currently does at a later time.
On another note:
What is the reason for the `MockedRepository` class extending a `TeeRepository`? Wouldn't it be better to directly return an instance of `MockRepository`?
=> Remove the access to the cached repository from outside the RepositoryManager

phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/MappedListTest.java
Hi guys!
The current version does not build (at least on Arch Linux) because of a missing import in MappedListTest.java.
I've fixed that and now it works.
=> fixed MappedListTest

phoenicis-apps/src/main/java/org/phoenicis/apps/MergeableRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/MultipleRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/TeeRepository.java, phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/MappedListTest.java
This PR replaces the array used in `MultipleRepository` with a list and should therefore fix #701.
In addition this PR adds the missing `Ignore` import in `MappedListTest`.
=> Replaced the array in MultipleRepository with a list

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySideBar.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/hidpi/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css
This PR connect to #715, it moves the code corresponding to the sidebar in the "Apps" tab to its own class. In addition adds css for the "All" categories toggle buttons.
While adding the css I discovered, that we don't have an "All" icon for the darkbreeze theme, I couldn't find on inside the faenza icon theme too.
=> Refactoring the Apps tab sidebar

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindow.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftToggleGroup.java
This PR moves the sidebar code from the `EnginesView` to its own class `EngineSideBar`.
In addition it introduces the `LeftToggleGroup` class in the engines sidebar to show the different engine categories.
=> Refactoring and improving the engine side bar

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/settings/SettingsController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/AboutPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/FileAssociationsPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/NetworkPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/SettingsSideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/UserInterfacePanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/ViewSettings.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/hidpi/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css
This PR refactors the "Settings" tab. This includes moving some functionality to new classes.
In this PR I've also tried to use `-fx-background-image` for the refresh icon in the "Refresh Repositories" button. The problem is that it didn't want to work, which is the reason why I'm still using `-fx-graphic`.
It would be nice if someone else could change `-fx-graphic` with `-fx-background-image`, because it seems like I don't get it working with `-fx-background-image`.
=> Refactoring the "Settings" tab

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/AdhocList.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftToggleButton.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftToggleGroup.java, phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/AdhocListTest.java
This PR does the following:
- refactored the LeftToggleGroup
- added an automatic removal from the ToggleGroup after a ToggleButton has been removed from the LeftToggleGroup
- added an AdhocList that combines an ObservableList with a number of normal objects to a new ObservableList
- improved the LeftToggleButton class to only fire an event after a click if the button isn't selected!
=> Refactored and improving the LeftToggleGroup

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java
This PR addresses #774.
In addition this PR makes a bug in the css for the refresh button visible. I guess it's because something with the padding is wrong.
How do we want to handle a height increase of the window? Should the height of the list increased too in this situation?
=> Changed Repository List in the Settings to scale with the window

phoenicis-apps/src/main/java/org/phoenicis/apps/dto/ApplicationDTO.java, phoenicis-apps/src/main/java/org/phoenicis/apps/repository/ClasspathRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/repository/LocalRepository.java, phoenicis-apps/src/main/java/org/phoenicis/apps/repository/MergeableRepository.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widget/MiniatureListWidget.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widget/StaticMiniature.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.css, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.css, phoenicis-library/src/main/java/org/phoenicis/library/LibraryManager.java, phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java, phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutDTO.java
This PR replaces the byte arrays, that contain the image data corresponding to shortcuts and applications with `URI` objects.
The result now looks like this:
I know that the proportions are a bit off now. It would be nice if someone can correct them at a later time.
A follow up PR should concentrate on the problem with the ShortcutDTO content.
When a `ShortcutDTO` is created, it receives the `URI` objects from the corresponding `ApplicationDTO` object. Only after a restart at a later time the URI will be corrected to link to a copy of the icon/miniature that belongs to the shortcut.
=> Replaced byte[] with icon and miniature data in ApplicationDTO and ShortcutDTO with URI objects

phoenicis-apps/pom.xml, phoenicis-cli/pom.xml, phoenicis-configuration/pom.xml, phoenicis-containers/pom.xml, phoenicis-dist/pom.xml, phoenicis-engines/pom.xml, phoenicis-entities/pom.xml, phoenicis-javafx/pom.xml, phoenicis-library/pom.xml, phoenicis-multithreading/pom.xml, phoenicis-scripts/pom.xml, phoenicis-settings/pom.xml, phoenicis-tests/pom.xml, phoenicis-tools/pom.xml, phoenicis-win32/pom.xml, pom.xml, settings/version-rules.xml
via `mvn versions:use-latest-releases`, now with a rules.xml to exclude beta, alpha etc.
fixes #768
=> use latest release of dependencies

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/MainWindowView.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationSideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerSideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ViewContainers.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSubCategoryTab.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/ViewEngines.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/SettingsSideBar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftListWidgetChooser.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftScrollPane.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/LeftSideBar.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less
This PR does the following:
- changed `LeftSideBar` and its inheritors to extend `BorderPane` instead of `ScrollPane`
- added a `LeftListWidgetChooser` to all all tabs except the settings
- used a scroll pane for everything that scales with its content (`LeftToggleGroup` for example) **inside** the sidebar, instead of using a scroll pane for the whole sidebar
Some interesting findings:
- when using a `ScrollPane` inside a `BorderPane` the padding from the `BorderPane` gets ignored... I solved this by adding a padding to the scrollpane inside the sidebar via css
Some images:
=> Added buttons to switch between the list widgets to all tabs except the settings tab

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less
Removed ugly border of the clean button in the search box.
=> fixed search clean button in Unity theme

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/icons/IconsListElement.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/icons/IconsListWidget.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/dark/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less
fixes #809
Also, added `selected` state to dark and Unity themes:
=> use pseudo class for "selected" state of icons list element

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less
=> Unity theme: use white text for selected tabs and category buttons

phoenicis-javafx/pom.xml, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/AddRepositoryDialog.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/RepositoriesPanel.java, phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java, phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/MergeableRepository.java, phoenicis-tools/src/main/java/org/phoenicis/tools/system/terminal/MacOSTerminalOpener.java
This PR fixes #776.
My problem with the taken approach is the used library `controlsfx`.
This library provides a `Wizard` component, which I'm using to divide the repository addition process in two parts:
1. The selection of the repository type (git, classpath, local)
2. The input phase of repository type dependent information (git url, classpath, file path)
This wizard restricts us in some aspects. One such aspect is the used css styles. The only way we can bind a stylesheet to the wizard seems to be to bind it to all the wizard steps. The same is true for the definition of a size for the wizard dialog.
My last and greatest problem is the provided translation from `controlsfx`. This translation has some "minor" bugs, like a misspelling of `Nächster`. In addition the chosen translations …
=> Add a gui dialog for the addition of repositories

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/settings/AddRepositoryDialog.java, phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryConfiguration.java, phoenicis-repository/src/main/java/org/phoenicis/repository/location/GitRepositoryLocation.java, phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/GitRepository.java
This PR fixes #857.
To support the creation of multiple git repositories with the same url and different branches, the branch name is now also included in the calculation of the of local repository folder name.
In addition this PR does some small cleanup on the variable names in `GitRepository`.
=> Use git branch when cloning a git repository

phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutCategoryDTO.java, phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ApplicationDTO.java, phoenicis-repository/src/main/java/org/phoenicis/repository/dto/CategoryDTO.java, phoenicis-repository/src/main/java/org/phoenicis/repository/repositoryTypes/LocalRepository.java, phoenicis-repository/src/test/java/org/phoenicis/repository/repositoryTypes/TeeRepositoryTest.java
To avoid problems with IDs such as `arcade games` which would create the invalid button ID string `#arcade gamesButton` (would be interpreted as a tag with the ID `arcade`, which contains another element `gamesButton`).
=> restrict DTO IDs to letters and numbers

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
Fixes issue that tab of the installation wizard is closed before the installation is finished (see PlayOnLinux/Scripts#260).
=> create TabPane in ViewLibrary only once

phoenicis-configuration/src/main/java/org/phoenicis/configuration/localisation/Localisation.java, phoenicis-configuration/src/main/java/org/phoenicis/configuration/localisation/PropertiesResourceBundle.java
Before, calling `setAdditionalTranslations` replaced the `ResourceBundle` for the translation. Therefore, the script translations overwrote the software translations. This worked most of the time because the GUI had been translated already. However, any string of the software which was created afterwards did not get translated (e.g. "Installers" in `AppPanel`).
=> fixed missing translations

phoenicis-configuration/src/main/resources/Linux.properties, phoenicis-configuration/src/main/resources/Mac OS X.properties
fixes #932 
Although we will never be able to perfectly adjust the width of the application window (e.g. due to different width of the sidebar because of translation), this PR should improve the appearance with default settings in the majority of cases.
=> fixed default window width

phoenicis-repository/src/main/java/org/phoenicis/repository/dto/ApplicationDTO.java
We do not want e.g. a screenshot to show up in the miniature view if there is no main miniature.
fixes #859
=> use default miniature if "main.png" does not exist

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
If no icon for the engine category is available in the theme, the "icon.png" from the repository is used.
fixes #792 
For the screenshot below, I removed `#wineButton` from the theme and added the `icon.png` from "Games" to "Engines/Wine".
=> use engine category icon from repository as fallback

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationFilter.java
The ApplicationFilter can now handle ApplicationDTO containing null values. This can happen e.g. if the application.json could not be read or is incomplete. Before, Phoenicis crashed with NullPointerException.
=> application filter: handle incomplete ApplicationDTO

phoenicis-tools/src/main/java/org/phoenicis/tools/http/Downloader.java
Allows to check whether a URL contains a newer version of a downloaded file.
=> added isUpdateAvailable to Downloader

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerInformationTab.java
Changing the engine version does not work currently, so the combobox suggests functionality which is not there. Moreover, fetching available engines from the Wine webservice causes performance issues on systems with slow Internet connection.
fixes #974
=> removed engine combobox in container information tab

phoenicis-configuration/pom.xml, phoenicis-configuration/src/main/java/org/phoenicis/configuration/PhoenicisGlobalConfiguration.java, phoenicis-configuration/src/main/resources-filtered/phoenicis.properties, phoenicis-configuration/src/main/resources/Linux.properties, phoenicis-configuration/src/main/resources/Mac OS X.properties
E.g. user.home may not be expanded during build, otherwise it will only be correct for the user who built the application at runtime.
fixes #991
=> split filtered and not filtered resources

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less
The minimum width is chosen such that one miniature is still completely visible.
=> set minimum width for icon list

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/DetailsView.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerToolsTab.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java
- avoid big preferred width from rightPane CSS
- avoid many columns in TilePane
fixes #1000
=> fixed details view width

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/DelayedFilterTextConsumer.java
The minimum search string length had been implemented to avoid performance problems at a time when every search rebuilt the whole applications list. However, this is not required anymore with the current `FilteredList` solution.
fixes #1037
=> removed minimum search string length

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/PhoenicisFilteredList.java, phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/PhoenicisFilteredListTest.java
When trying to add a local repository I got an exception.
This PR should fix this.
My guess is, that the `setAll` method of the observable list cleared the source observable list, before the event was triggered for the filtered list. This resulted in "bad" calls to `getSource().get(index)`.
=> Fixed a bug in the filtered list that appeared when you try to add a new repository

phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less
=> Unity theme: removed border of search clean button

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java
Use a preferred width of 1/3 of the window width (3 columns: sidebar, content, details). If the window is too small, the text will still be unreadable because minimum size of sidebar and content push the details view out of the window.
fixes #1053
=> fixed width of details view

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/compact/CompactListWidget.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/widgets/lists/details/DetailsListWidget.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/installations/ViewInstallations.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/main.less
fixes #1019 
It's not possible to use the same CSS for the icons list because it's a `ScrollPane` (details list and compact list are `GridPane`).
=> use same hover/selected colors for all list widgets

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/CreateShortcutPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/EditShortcutPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySidebar.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/ViewLibrary.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/default/main.less, phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutCreationDTO.java
requires PhoenicisOrg/Scripts#376
When you click "Create shortcut" in the library sidebar, a new details view opens:
If you do not fill the form properly, it marks the wrong fields and shows an error message in a tooltip:
fixes #1060
=> added possibility to configure new shortcut when creating it

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/AdhocList.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/ExpandedList.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/lists/PhoenicisFilteredList.java
Fixes #1076. The `trigger` method is now based on the `update` method in `FilteredList`, with the only changes that it checks the whole list for updates and doesn't call `nextUpdate` if the value fulfilled the filter condition before and after the check.
In addition I've fixed the permutation range in some `permute` methods.
=> Improve the performance of PhoenicisFilteredList

phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java
requires PhoenicisOrg/Scripts#391
This approach allows us to define the engine specific tools directly in JS. We can use it later to implement a generic engine tools tab in the "Containers" view.
=> define Wine tools in JS

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EngineSubCategoryTab.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesFilter.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesView.java
Fixes #1097, fixes #1096. In addition the engine sub categories are now ordered alphabetically.
This is quite fun to use. ;D
=> Improve and refactor EnginesView

phoenicis-containers/src/main/java/org/phoenicis/containers/wine/WinePrefixContainerController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerToolsTab.java
We have it in "Library" now. There you can also edit the new shortcut directly.
=> removed "create shortcut" from "Containers" tab

phoenicis-engines/src/main/java/org/phoenicis/engines/EngineToolsManager.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanelFactory.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java
Fixes the problem that engine tools and engines could not be loaded if "Engines" was translated. Also: if no engine tools are available, the "Engine tools" tab in the container view is not shown.
fixes #1122
=> fixed generic engines and engine tools

phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java
As e.g. the shortcut miniature file for 7-zip is called "7zip.miniature", the miniature was lost when editing the shortcut.
=> fixed baseName in updateShortcut()

phoenicis-settings/src/main/java/org/phoenicis/settings/Setting.java, phoenicis-settings/src/main/java/org/phoenicis/settings/SettingsManager.java, phoenicis-tools/src/main/java/org/phoenicis/tools/system/SystemConfiguration.java
For example on Mac OS, `tools.linux-terminal` does not exist (also not required). Use an empty String as default in these cases.
fixes #1139
=> set default value if tools.linux-terminal does not exist

README.md
Just a simple one, poking around POL and saw you guys run TravisCI so you may as well broadcast your build status. I always find it helps me determine the health of an OS project. I would have added the Codacy badge as well but it appears you have to have access to the profile itself, which I do not. Context:
https://support.codacy.com/hc/en-us/articles/212799365-Badges
Cheers.
=> add travisci build status badge to readme

.eslintrc.yml
We have .js files for testing in phoenicis-tests/src/main/resources/org/phoenicis/tests. Therefore, we must adjust ESLint settings for Codacy.
=> added .eslintrc.yml

.travis.yml
If a branch from this repository (not a fork) shall be merged, Travis would execute the checks twice (see e.g. the PRs from dependabot).
=> Travis: avoid double builds on pull requests

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibrarySidebar.java
The button does not work currently, so this PR disables it to avoid confusion. See #1179.
=> Disable "run script" button

pom.xml
Reverts PhoenicisOrg/phoenicis#1213
Running `mvn clean package` changes the formatting of many files. The config file does not seem to be considered.
=> Revert "Bump net.revelc.code.formatter:formatter-maven-plugin from 2.0.1 to 2.7.2"

.travis.yml
Travis output:
```
Gem::RuntimeRequirementNotMetError: github-pages-health-check requires Ruby version >= 2.2.0. The current ruby version is 2.1.0.
Gem::RuntimeRequirementNotMetError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2. The current ruby version is 2.1.0.
```
=> Use Ruby 2.5 for Travis CI GitHub Pages check

phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/ViewsConfiguration.java, pom.xml
Currently, it is not possible to build if the Phoenicis Maven project is not a git repository (e.g. if you just downloaded the .zip from GitHub) because the `buildNumber` variable is not set by buildnumber-maven-plugin.
fixes #1340
=> Fix build if Maven project is not a git repository

docs/_docs/Users/build.md
As discussed here: https://github.com/PhoenicisOrg/phoenicis/issues/1157
=> Document that currently Oracle Java is required to build and run Phoenicis on Fedora.

.travis.yml
Makes it easier to distinguish the builds for the different combinations of OS and JDK.
=> Travis: use job names

.travis.yml, pom.xml
see https://issues.apache.org/jira/browse/SUREFIRE-1588
This should be reverted as soon as the surefire bugfix is available.
fixes #1447
I do not understand why the change in the pom.xml does not work. It is working for me locally. Looking at the logs, it seems that Travis uses surefire 2.17 and not 2.22.1. Not sure if that's ok...
=> Implement workaround for surefire bug 1588

.travis.yml, pom.xml
Reverts PhoenicisOrg/phoenicis#1464
The pull request build was passing but on master the issue occurred again. I don't know why this is the case but probably we should just live with the workaround for now.
=> Revert "Revert "Implement workaround for surefire bug 1588""

.travis.yml
Java 10 is the default on the .deb target OS (Ubuntu 18.04)
=> Travis: build .deb with Java 10

phoenicis-repository/src/main/java/org/phoenicis/repository/types/GitRepository.java
NOTE: The lock is acquired only for the complete JVM, so it's not a replacement for the `synchronized` block.
fixes #1463
=> Lock git folder during clone/update

phoenicis-dist/src/flatpak/org.phoenicis.javafx.json
Previously, the `.Phoenicis` folder was located in the flatpak runtime environment. Now it uses the "normal" one in the user home. Thus you can share apps, settings etc. regardless if you run the flatpak or deb etc. Moreover, it is persistent if the flatpak is updated/uninstalled.
=> Flatpak: use user home

phoenicis-tools/src/main/java/module-info.java
=> Fix: cannot access TerminalOpener from Javascript with Java 10+

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationsView.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerEngineToolsTab.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/ContainerPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesView.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/installations/InstallationsView.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryView.java
Resizes the details view based on the window size. Therefore, the details view is still usable even with a very small window.
fixes #1541
fixes #1410
=> Fix details view size

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java
Currently the loading process of the engines for the engines tab is strange.
The engine categories are loaded without their subcategories.
This in turn should prevent them from showing up in the sidebar of the engines tab, because they are then assumed to be empty.
This PR solves this problem by additionally fetching all subcategories of the fetched engine categories, before the engines tab is populated.
This PR is part of #1536
=> Fix fetching process of the engines before the engines tab is populated

phoenicis-javafx/src/main/java/org/phoenicis/javafx/collections/ConcatenatedList.java, phoenicis-javafx/src/test/java/org/phoenicis/javafx/views/common/lists/ConcatenatedListTest.java
This PR adds a `ConcatenatedList` class to Phoenicis, which fixes #1565.
The new `ConcatenatedList` class changes in the number of lists it concatenates and in the concatenated lists themselves.
=> Add a concatenated observable list implementation

pom.xml
The keys.pot is not updated during the Maven build anymore.
=> Remove unused maven-replacer-plugin

phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
Pulseaudio socket is needed to support audio output/input in flatpak installation.
This fixes #1840
=> Add pulseaudio permission to flatpak

phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
I just read the flatpak documentation about [Sandbox Permissions](http://docs.flatpak.org/en/latest/sandbox-permissions.html). Here is written:
```
While not ideal, --device=all can be used to access devices like controllers or webcams.
```
I have not tested this yet, but missing controller support would probably have been noticed sooner or later.
=> Relax flatpak device permissions for controller access

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainerEngineSettingsPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainerEngineToolsPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainerOverviewPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainerToolsPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainerVerbsPanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainersSidebarToggleGroup.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/engine/skin/EngineInformationPanelSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/ShortcutEditingPanelSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/ShortcutInformationPanelSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/utils/CollectionBindings.java
This PR:
- adds a `mapToMap` function to the `CollectionBindings` class
- replaces custom methods with `mapToMap` calls
- replaces custom methods with `mapToList` calls
- removes some unnecessary constructors
=> Refactor some JavaFX components

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/skin/ContainerVerbsPanelSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/setting/skin/RepositoriesPanelSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/dialogs/ConfirmDialog.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/dialogs/ErrorDialog.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/dialogs/ListConfirmDialog.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/dialogs/SimpleConfirmDialog.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryView.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/scriptui/UiQuestionFactoryJavaFX.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/standard/main.less
This PR:
- renames `ConfirmDialog` to `SimpleConfirmDialog`
- adds a new abstract `ConfirmDialog` class
- adds a `ListConfirmDialog` class
- improves the dialog classes
This PR closes #1822.
Screenshot:
=> Add ListConfirmDialog class

phoenicis-library/src/main/java/org/phoenicis/library/ShortcutRunner.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/JSAScriptEngine.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/PhoenicisScriptEngine.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/PhoenicisScriptEngineFactory.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/PolyglotScriptEngine.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/ScriptEngineType.java
This PR:
- makes `PhoenicisScriptEngine` an interface
- adds two specific implementations for `PhoenicisScriptEngine` (one based on the Java Scripting API and another one for Polyglot engines)
=> Add phoenicis script engine interface

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/application/control/ApplicationsFeaturePanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/application/skin/ApplicationsFeaturePanelSkin.java
This PR fixes a bug where a click on the close button in the details panel of the applications tab leads to an exception.
=> Fix the close button in the application details panel

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/application/skin/ApplicationSidebarToggleGroupSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/skin/SidebarToggleGroupBaseSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/engine/skin/EnginesSidebarToggleGroupSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/installation/skin/InstallationsSidebarToggleGroupSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/LibrarySidebarToggleGroupSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/standard/main.less
Use full category ID in kebab-case for category button ID. This avoids potential naming conflicts e.g. between applications and engines (there could be something like `applications.wine` and `engines.wine`).
fixes #1874
=> Fix missing category icons

phoenicis-dist/pom.xml
Fixes error message:
```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module org.bouncycastle.pg contains package org.bouncycastle.openpgp, module bcpg.jdk16 exports package org.bouncycastle.openpgp to org.bouncycastle.pg
```
=> Fix duplicate exports (Phoenicis does not start from IntelliJ IDEA)

phoenicis-dist/src/scripts/phoenicis-create-package.sh
They are not provided by the runtime due to crash.
=> Add winbind and freetype to the .deb

phoenicis-dist/src/scripts/phoenicis-create-package.sh
Those libs does not work from runtime so they have to be dependency.
=> Update .deb generation for missing libs

phoenicis-containers/src/main/java/org/phoenicis/containers/GenericContainersManager.java
This PR changes the called method on `ShortcutReader` from `container()` to `getContainer()` during the deletion of a container. The reason for the change is that `container` has been defined as a getter method which needs to be accessed like a member field, which is semantically wrong.
This PR needs to be merged together with https://github.com/PhoenicisOrg/scripts/pull/1042, which also contains additional information.
=> Fix a "TypeError" Exception when deleting a Wine Container

phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java
This PR changes the signature of the `include` operation to return an object. In other words it changes:
```java
void include(String scriptId);
```
to:
```java
Object include(String scriptId);
```
The returned value of the `include` command is the result of the last executed command inside the referenced script.
=> Change Signature of the "include" Command to return an Object

phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/ScriptEngineType.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/implementation/PolyglotScriptEngine.java
This PR adds support for some more automatic conversions from Java types to JS types (for example Java `List` to JS `Array`). See also https://github.com/graalvm/graaljs/issues/88 for more details.
I expect this to allow us to remove almost all `Java.from` operations.
=> Add Support for automatic Object Conversion from Java to JS

phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java
With the old implementation, the `IncludeInjector` would return `null` if the same path has already been included before.
=> Fix JS includes (avoid null return if script already included)

phoenicis-containers/src/main/java/org/phoenicis/containers/GenericContainersManager.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/control/LibraryFeaturePanel.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/library/LibraryView.java, phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java, phoenicis-library/src/main/java/org/phoenicis/library/ShortcutRunner.java, phoenicis-repository/src/test/java/org/phoenicis/repository/types/ClasspathRepositoryTest.java, phoenicis-repository/src/test/resources/org/phoenicis/repository/repositoryTest/Applications/Graphics/Photofiltre/Online/script.js, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java
This PR adds a simple module system to `include`.
When using this PR every script loaded via `include` needs to export their values explicitly to the calling script. To export a value `x` and `y` you can call the following inside the included script:
```javascript
module.x = <<first value to export>>;
module.y = <<second value to export>>;
```
In case only a single value is exported `module.default` can be used:
```javascript
module.default = <<single export>>;
```
The exported values can then be included as followed:
```javascript
// for a "default" export:
const Value = include(...);
// do something with Value
// for multiple exports:
const {x, y} = include(...);
// do something with x and y
```
=> Add a simple Module System for "include"

phoenicis-tools/src/main/java/org/phoenicis/tools/ToolsConfiguration.java, phoenicis-tools/src/main/java/org/phoenicis/tools/processes/PhoenicisProcess.java, phoenicis-tools/src/main/java/org/phoenicis/tools/processes/PhoenicisProcessBuilder.java, phoenicis-tools/src/main/java/org/phoenicis/tools/processes/ProcessUtils.java
This PR adds a new `ProcessUtils` class which can be used as a `Bean` from the scripts to start new processes (see also #2015)
=> Add a ProcessUtils Class

phoenicis-engines/src/main/java/org/phoenicis/engines/Verb.java, phoenicis-engines/src/main/java/org/phoenicis/engines/VerbsManager.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/EngineInjector.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/injectors/IncludeInjector.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/exceptions/CircularIncludeException.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/exceptions/IncludeException.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/exceptions/ScriptException.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/exceptions/ScriptNotFoundException.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/interpreter/ScriptFetcher.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/ui/Message.java, phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/UiSetupWizardImplementation.java
This PR:
- adds three new exceptions to the script engine: CircularIncludeException, IncludeException and ScriptNotFoundException
- checks for circular includes (fixes #2048)
- throws a dedicated exception when an include fails (#2056)
- moves the exceptions to a new subpackage
Open issues:
The PR works, but our exception processing seems to be a bit strange. In some cases it seems like only parts of the exceptions are shown to the user. Sometimes the terminal contains a different GUI-based exception instead of the `ScriptException`. In addition it seems like the previous `throwException` wrapped every given exception into an additional `ScriptException` which makes understanding the shown exceptions more difficult.
=> Improve User Friendliness of the "include" Operation

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainerVerbsPanel.java
This PR sorts the verbs in the container verbs panel according to the verb names. This is something that has annoyed me for a long time now!
=> Sort the Verbs in the ContainerVerbsPanel according to their Names

phoenicis-engines/src/main/java/org/phoenicis/engines/VerbsManager.java
This PR is required to install verbs directly from the GUI after the changes in https://github.com/PhoenicisOrg/scripts/pull/1112.
=> Introduce the Module System to the Verbs

phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/containers/ContainersController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/MainWindow.java, phoenicis-repository/src/main/java/org/phoenicis/repository/DefaultRepositoryManager.java, phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryManager.java
fixes #2037
load repository only if it is really required, i.e.
- if one of the following tabs is opened
and
- if the repository has not been loaded already (avoid reload by opening the tab several times)
tabs:
- apps (apps are stored in the repository)
- containers (engine settings etc.)
=> Load repository only if required

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/application/skin/ApplicationSidebarToggleGroupSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/LibrarySidebarToggleGroupSkin.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/ControllerConfiguration.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/MainController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/apps/AppsController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/library/LibraryController.java, phoenicis-javafx/src/main/java/org/phoenicis/javafx/themes/ThemeManager.java, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/breezeDark/main.less, phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/standard/main.less, phoenicis-library/src/main/java/org/phoenicis/library/LibraryManager.java, phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java, phoenicis-library/src/main/java/org/phoenicis/library/dto/ShortcutDTO.java, phoenicis-repository/src/main/java/org/phoenicis/repository/DefaultRepositoryManager.java, phoenicis-repository/src/main/java/org/phoenicis/repository/RepositoryManager.java
fixes #1626
requires https://github.com/PhoenicisOrg/scripts/pull/1159
We cannot use the default category buttons (of the apps) in the library tab for several reasons:
- It cannot be guaranteed that the repository which contained the category of a certain app does still exist after the app has been installed (e.g. the repository might have been deleted).
- It should not be required to fetch the repository to use the library.
Therefore, use the following approach:
- When installing an app, store the icon for its category together with the shortcut (i.e. in the library).
- Use this icon as fallback if the theme does not specify an icon for this category.
It is necessary to store the category icon per shortcut, otherwise category icons in the library could be overwritten if multiple …
=> Fix library category icon handling

phoenicis-tools/src/main/java/org/phoenicis/tools/files/FileUtilities.java
fixes https://github.com/PhoenicisOrg/scripts/issues/1162
It seems that this behavior was intended anyways because we use
```Java
Files.deleteIfExists(fileToDelete.toPath());
```
=> FileUtilities#remove(): do nothing if file does not exist

phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/control/LibraryFeaturePanel.java, phoenicis-tools/src/main/java/org/phoenicis/tools/http/Downloader.java, phoenicis-tools/src/main/java/org/phoenicis/tools/http/PhoenicisUrlConnection.java
fixes #1807
The problem was that two connections for the Wine versions json are opened. The first to check if an update is available (`Downloader#isUpdateAvailable()`), the second to actually download the file (`Downloader#get()`). If e.g. `Downloader#isUpdateAvailable()` does not open a connection but returns `true` immediately, the download in `Downloader#get()` starts directly.
I'm not completely sure what happens in the background but my assumption is that the underlying socket is closed by the `disconnect` such that the next connection can setup a new socket immediately.
=> Downloader: close URL connection after download

docs/_docs/Developers/packages.md, phoenicis-dist/src/flatpak/distribution.xml, phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
Install only .jar's in `phoenicis-dist/target/lib` to avoid issues with split packages etc.
=> Fix flatpak

phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
Add [rxvt](https://sourceforge.net/projects/rxvt/) terminal emulator such that terminal can be opened from engine tools in the containers tab.
fixes #2223
=> Flatpak: add terminal emulator

phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
GL32 deps need to be updated to properly detect Nvidia graphics.
see https://github.com/flathub/org.phoenicis.playonlinux/pull/14
=> Fix Nvidia detection

i18n/keys.pot, phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/container/control/ContainersFeaturePanel.java
In string [#2334](https://crowdin.com/translate/phoenicis/3/en#2334)
––––––––––
Off-topic: Hebrew is 100% now. May you review the translations and add them to the official release, please?
=> Fix "engine" written twice

pom.xml
avoid `TypeError: (intermediate value).from is not a function` in https://github.com/PhoenicisOrg/scripts/blob/6bccb916f7d0942b68f34ade128e4248336844ab/Engines/Wine/Engine/Versions/script.js#L26
=> Revert GraalVM to 21.0.0

phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
runtime 20.08 is end-of-life
fixes #2593
Thanks to @proletarius101 for providing the fix in https://github.com/flathub/org.phoenicis.playonlinux/pull/16 and testing it.
=> Flatpak: update runtime to 22.08

.github/workflows/merge-me.yml
As described in https://github.com/ridedott/merge-me-action/issues/1212, the action runs as soon as **any** workflow in `workflows` completed. This means that it usually ran after linting the Java files and thus ignored if the CI failed.
Ignoring the linting workflow is not optimal. However, the current behavior is way worse. Also, merge-me is meant for dependabot PRs which should not produce linting issues in general.
=> merge-me action: check only CI

pom.xml
Reverts PhoenicisOrg/phoenicis#2598
build fails with `class file has wrong version 61.0, should be 55.0`
=> Revert "Bump spring.version from 5.3.23 to 6.0.0"

.github/workflows/ci.yml, README.md, phoenicis-javafx/pom.xml
The currently used [lesscss-maven-plugin](https://github.com/gabrysbiz/lesscss-maven-plugin) is dead and causes the build to fail.
fixes #2643
=> Use activeweb-lessc-maven-plugin

.github/workflows/ci.yml
The build failed with:
```
Err:7 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libavahi-glib1 amd64 0.7-4ubuntu7.1
404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/avahi/libavahi-glib1_0.7-4ubuntu7.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
=> CI: use ubuntu-latest for Flatpak build

.github/workflows/ci.yml, .github/workflows/linter.yml, .github/workflows/update-translations.yml
fixes:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
=> CI: update actions/checkout to v3

.github/workflows/linter.yml
fixes:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: EndBug/add-and-commit@v6. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
=> CI: update EndBug/add-and-commit to v9

.github/workflows/ci.yml
fixes:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
=> CI: update actions/upload-artifact to v3
